### ISSUE TITLE
Add support for UDT subfields in LWT expression

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#13624]
Cassandra added in 2016 (Cassandra 3.6) support for using individual subfields of a UDT in expressions, and in particular LWT expressions. See https://issues.apache.org/jira/browse/CASSANDRA-7423 and commit https://github.com/apache/cassandra/commit/677230df694752c7ecf6d5459eee60ad7cf45ecf

For example, one can do `IF v.a = 0` when `v` is a UDT and `a` is one of its fields.

This doesn't work in Scylla. Our Cql.g supports in `columnCondition` only a `subscriptExpr` (a subscript `col[term]`) but not a UDT subfield `v.a`.

I consider this issue a bug and not an "enhancement", because I think users will consider it a bug that an expression syntax is supported in some situations but not in others. What is most surprising is that our Cql.g **does** include many of the cases of subfields added in  https://github.com/apache/cassandra/commit/677230df694752c7ecf6d5459eee60ad7cf45ecf - for example `unaliasedSelector` (SELECT expression) and `columnOperationDifferentiator`  (SET), but for some reason only the LWT support for it is missing. Maybe we forgot to do it when adding LWT support to our parser, or this feature was somehow lost (a regression?) during the recent CQL parsing cleanups?

Reproduced by the translated Cassandra unit test `cassandra_tests/validation/operations/insert_update_if_condition_collections_test.py`::`testUDTField`.

**Comment by nyh** [comment]
According to https://github.com/scylladb/scylladb/pull/13480#issuecomment-1527831955 by @cvybhu, as soon as this issue is fixed, https://github.com/scylladb/scylladb/issues/12906 can be marked fixed as well because this is the last thing that is supported by the CQL syntax but evaluate() can't do.

**Comment by cvybhu** [comment]
After #12906 it'll be possible to evaluate field selections, which should help with this issue, but it doesn't solve it completely yet.

There's two more things that should be done:
* Modify grammar in `Cql.g`. Right now it's impossible to write `column.field` inside the `IF` statement, as there's no grammar rules for it.
* There's no `prepare_expression(field_selection)` yet, trying to prepare a `field_selection` will cause an `on_internal_error`. I'm not 100% sure that it's needed for column conditions, but it's likely that it is. This will be implemented as a part of https://github.com/scylladb/scylladb/issues/12907
