### ISSUE TITLE
CDC generation data inconsistency in dtest

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#15024]
```
failed on teardown with "AssertionError: Unexpected errors found: [('node8', ['ERROR 2023-08-11 10:21:39,990 [shard 0] cdc - Could not retrieve CDC streams with timestamp (2023/08/11 10:21:54, 646574cb-bbd2-4f2b-9984-420e8de4a6c8) upon gossip event. Reason: "std::runtime_error (read_cdc_generation: wrong number of rows. The `num_ranges` column claimed 2048 rows, but reading the partition returned 1000.)". Action: not retrying.'])]"
```

and

```
AssertionError: Vnodes should contain generation token ranges
assert {-9221759040674424859, -9221191817084739451, -9214398929551407821, -9208884236435286274, -9202041168258869393, -9199232153913659666, ...} <= {-9221759040674424859, -9221191817084739451, -9214398929551407821, -9202041168258869393, -9199232153913659666, -9195429929198872027, ...}
```

[logs-full.release.015.zip](https://github.com/scylladb/scylladb/files/12321623/logs-full.release.015.zip)

First seen on 2af146bbaa0efb876a4d173e7475764cf85ee163 (PR CI) which is based on master d1d1b6cf6e012143511a91e0170d7d1c6d89ffaa

Then seen on next 17c1b15c81b732f9641575f5198c375de4610999 with similar log error:
```
    failed on teardown with "AssertionError: Unexpected errors found: [('node6', ['ERROR 2023-08-11 11:06:36,921 [shard 0] cdc - Could not retrieve CDC streams with timestamp (2023/08/11 11:06:51, e3f5c3f1-5ed5-43bc-a284-73410639e13e) upon gossip event. Reason: "std::runtime_error (Could not find CDC generation (2023/08/11 11:06:51, e3f5c3f1-5ed5-43bc-a284-73410639e13e) in distributed system tables (current time: 2023/08/11 11:06:36), even though some node gossiped about it.)". Action: not retrying.']), ('node8', ['ERROR 2023-08-11 11:06:37,235 [shard 0] cdc - Could not retrieve CDC streams with timestamp (2023/08/11 11:06:51, e3f5c3f1-5ed5-43bc-a284-73410639e13e) upon gossip event. Reason: "std::runtime_error (read_cdc_generation: wrong number of rows. The num_ranges column claimed 2048 rows, but reading the partition returned 2000.)". Action: not retrying.'])]"
```

This:
```
The `num_ranges` column claimed 2048 rows, but reading the partition returned 1000.)"
```
is a sanity check when we query CDC generation data from `system_distributed_everywhere.cdc_generations_v2`. The static row `num_ranges` claims that the generation should have 2048 rows, but the query returned 1000 rows. Curious: isn't 1000 the page size?

In the other failure we saw 2000 rows which would in that case be a multiple of page size.

Is the query returning only a subset of pages for some reason?

**Comment by kbr-scylla** [comment]
The failure was observed on: cdc_test.TestCdc.test_add_field_with_cdc[Multi_DC_cluster], cdc_test.py::TestCdc::test_simple_cdc_with_preimage[Multi_DC_cluster]

**Comment by kbr-scylla** [comment]
Fix was merged to dtest, closing.

**Comment by fruch** [comment]
> Most likely culprit:
> https://github.com/scylladb/scylla-dtest/commit/52c82fbe62f8969bb1e4c025c1ca5446057c0d59
> (the token ring has not converged when we were doing the CDC generation write)
> 
> ```
> commit 52c82fbe62f8969bb1e4c025c1ca5446057c0d59
> Author: Israel Fruchter <fruch@scylladb.com>
> Date:   Thu Jul 20 18:07:28 2023 +0300
> 
>     Speed up cluster boot using Scylla options
>     
>     Today, dtest starts a single node fairly quickly, but starting a multi-
>     node cluster is painfully slow - for example, test_boot_three_nodes
>     (which starts a 3-node cluster) takes 119 seconds.
>     
>     It turns out that the main reason for this slowness is that Scylla uses
>     sleeps of constant and completely arbitrary durations - 5 or 10 seconds -
>     waiting for "gossip to settle" when changing the cluster topology. But
>     dtest runs inside a single machine so has a 100% reliable and very low
>     latency network, and also does node operations one at a time, so all these
>     long sleeps are unnecessary. In this patch we use the configuration options
>     
>             skip_wait_for_gossip_to_settle: 0
>     
>     To eliminate these unnecessary sleeps.
>     
>     With this patch the 119-second run time of cluster with 3 nodes is down
>     to 15 seconds. If we measure only the cluster boot time and not overheads,
>     the ratio is even more impressive - from 115 seconds before this patch to
>     11 seconds.
>     
>     These numbers can be reduced further later (4 seconds to boot every node
>     is still sub-optimal), but it's a very good start.
>     
>     Fixes scylladb#2429
>     
>     This also add new marker named `no_boot_speedups` that can be used
>     to to disable this speedup, for those test that it currently
>     breaking them, until we'll figure out for each one, what
>     is the reason and how it can be handled.
>     
>     Signed-off-by: Nadav Har'El <nyh@scylladb.com>
> ```
> 
> 
> Curiously `test_add_field_with_cdc` and `test_simple_cdc_with_preimage` are **not** marked with  `@pytest.mark.no_boot_speedups` for some reason. Mistake? cc @fruch @nyh 

We did based on test results, not on validating the content of each test.

So if it's mostly working, we probably didn't noticed it, we might hit a few more of those in the coming days.

But we think it worth it. It cut the total  test runtime in half.

**Comment by nyh** [comment]
@fruch I just realized you forgot to apply my patch https://github.com/scylladb/scylla-dtest/commit/d30a8994c9031e8f5236633ba9fc8f39156b92f2 to cdc_test.py

The CDC tests weren't even waiting for the nodes to recognize each other - let alone for anything specific related to CDC. Please consider applying that patch as well instead of adding "no_boot_speedups" to everything. We'll regret the massive addition of these tags later when Raft comes and we forgot all the knowledge of these dtest bugs that we already debugged!

**Comment by nyh** [comment]
> > fix these bugs again when Scylla doesn't have those boot sleeps (e.g., when it uses Raft instead of gossip)
> 
> One of the reasons we want to use Raft for managing topology is so we can replace sleeps like "wait for `ring_delay` seconds and pray that token ring has converged by then" with explicit "barrier" commands that **force** the nodes to fetch the new topology (including token ring) before we proceed to the next step of the bootstrap procedure.
> 
> If these bugs appear again when we use Raft instead of gossip, it means we completely missed the mark.

You may be right regarding some of the tests, but not others. The thing is that the extra 20 second sleeps masked all sorts of missing waits. Not just for the topology - for example, a test might not wait for CDC to be available. Or a test might create a new with wait_other_notice=false by mistake - but just the 20 second sleep added in any case happened to be enough. There may be a dozen different tests that each needs to wait for a different condition - but the same 20 second sleep made all of these tests pass and now (sometimes) they don't.
