### ISSUE TITLE
make `removenode --force` do something sensible in raft-topology mode

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#16293]
Options:
- get rid of it completely (i.e. merge https://github.com/scylladb/scylladb/pull/15834)
- specify what it should do exactly, and follow the specification for raft topology

One idea is to just make it wait for any ongoing removenode operations to finish in raft-topology mode, and do nothing otherwise.

Another idea is to trigger a special type of removenode that skips streaming/repair, for disaster recovery scenarios (for example: we're quickly running out of disk space and need to get rid of a troublesome/dead node to bootstrap a new one).

Refs: https://github.com/scylladb/scylladb/pull/15834, https://github.com/scylladb/scylladb/issues/15799

**Comment by kbr-scylla** [comment]
cc @gleb-cloudius @bhalevy @asias

**Comment by kbr-scylla** [comment]
>  We/customers wanted it when they hit limitation/issues with replace, after full cluster restart that lost a number (3) of nodes and ignoring the other dead nodes for replace didn't work.

That's why it may be a good idea to have this special type of removenode even though there's replace -- just in case.

**Comment by gleb-cloudius** [comment]
> > We/customers wanted it when they hit limitation/issues with replace, after full cluster restart that lost a number (3) of nodes and ignoring the other dead nodes for replace didn't work.
> 
> That's why it may be a good idea to have this special type of removenode even though there's replace -- just in case.

But original problem is solved now with ignore_nodes param for replace, no?

**Comment by bhalevy** [comment]
> > > We/customers wanted it when they hit limitation/issues with replace, after full cluster restart that lost a number (3) of nodes and ignoring the other dead nodes for replace didn't work.
> > 
> > 
> > That's why it may be a good idea to have this special type of removenode even though there's replace -- just in case.
> 
> But the original problem is solved now with ignore_nodes param for replace, no?

No, using this param doesn't work as expected in this case due to https://github.com/scylladb/scylladb/issues/15787 that is not solved yet.

**Comment by gleb-cloudius** [comment]
> > > > We/customers wanted it when they hit limitation/issues with replace, after full cluster restart that lost a number (3) of nodes and ignoring the other dead nodes for replace didn't work.
> > > 
> > > 
> > > That's why it may be a good idea to have this special type of removenode even though there's replace -- just in case.
> > 
> > 
> > But the original problem is solved now with ignore_nodes param for replace, no?
> 
> No, using this param doesn't work as expected in this case due to #15787 that is not solved yet.

Looks like something irrelevant for the topology over raft.

**Comment by gleb-cloudius** [comment]
I do not see a use case for `removenode --force` in raft mode, but @kostja is against applying https://github.com/scylladb/scylladb/pull/15834 as is since he wants a deprecation period. We can throw an error in raft mode only and add deprecation warning for non raft mode. @asias

**Comment by kbr-scylla** [comment]
Fine for me.
