### ISSUE TITLE
Scylla fails to start with `Bad configuration: consistent_cluster_management requires schema commit log to be enabled`

### ISSUE THREAD

**Issue by igorribeiroduarte** [scylladb/scylladb#16427]
*Installation details*
Scylla version (or git commit hash): 5.4.0

In this version, by default, `consistent_cluster_management` is set to `true` while `force_schema_commit_log` is set to `false`.
This causes Scylla to fail with the error below unless we explicitly set `force_schema_commit_log` to `true`:
```
Dec 14 20:21:45 node1 scylla[10724]:  [shard 0:main] init - Bad configuration: consistent_cluster_management requires schema commit log to be enabled
```

**Comment by kbr-scylla** [comment]
@igorribeiroduarte is this an upgraded cluster or a new one?

cc @tgrabiec

**Comment by igorribeiroduarte** [comment]
> @igorribeiroduarte is this an upgraded cluster or a new one?
> 
> cc @tgrabiec

a new one, @kbr-scylla

**Comment by kbr-scylla** [comment]
@igorribeiroduarte conf/scylla.yaml in a new 5.4 cluster provides by default `force_schema_commitlog: true`; did you use a custom conf/scylla.yaml / removed some parameters?

**Comment by igorribeiroduarte** [comment]
> @igorribeiroduarte conf/scylla.yaml in a new 5.4 cluster provides by default `force_schema_commitlog: true`; did you use a custom conf/scylla.yaml / removed some parameters?

@kbr-scylla, I did use a custom `conf/scylla.yaml`, but I didn't set a value for `force_schema_commitlog`. If `force_schema_commitlog` is already set to `true` in `conf/scylla.yaml` why not also setting it to `true` in `db/config.cc` (https://github.com/scylladb/scylladb/blob/scylla-5.4.0/db/config.cc#L1066)?
This would solve the problem without me having to change the `scylla.yaml` template that I'm using for this cluster.

**Comment by kbr-scylla** [comment]
It was initially set to false in db/config.cc because it's unsafe to turn it on automatically during upgrades to 5.1 where it was introduced. It was only safe for new clusters. So by setting it to true in conf/scylla.yaml template, but false in db/config.cc, it is false for upgrades but true for new clusters -- assuming that new clusters are using the provided conf/scylla.yaml template.

IIUC The documented new cluster deployment procedure is using conf/scylla.yaml provided with the package. So new versions of Scylla provide new conf/scylla.yaml templates. Custom deployment scripts used by Cloud and whatnot should be following this. Or at least merge their custom templates with whatever new options are appearing in new versions of conf/scylla.yaml.

I'm not sure it's safe to set it to true in db/config.cc in 5.4. Maybe based on the supported upgrade paths it is. But if it's not necessary we should stay on the safe side.

@tgrabiec WDYT?

**Comment by kbr-scylla** [comment]
BTW. if you're using outdated conf/scylla.yaml for new clusters, it means that your new 5.2 clusters were started without Raft enabled -- which goes against what we planned in core, which was to enable it in new 5.2 clusters :(

Where were you using this custom conf/scylla.yaml?

@mykaul we should verify that Scylla Cloud is using new conf/scylla.yaml templates. Otherwise it might turn out that 5.2/2023.x clusters are actually running **without** Raft, that would be quite sad. Who can verify this?

cc @kostja

**Comment by igorribeiroduarte** [comment]
> It was initially set to false in db/config.cc because it's unsafe to turn it on automatically during upgrades to 5.1 where it was introduced. It was only safe for new clusters. So by setting it to true in conf/scylla.yaml template, but false in db/config.cc, it is false for upgrades but true for new clusters -- assuming that new clusters are using the provided conf/scylla.yaml template and upgraded clusters are using whatever conf/scylla.yaml they had from before upgrade.

But then what's the point of having `consistent_cluster_management` set to `true` by default in `db/config.cc`? Shouldn't this value always be compatible with the value set in `force_schema_commit_log`?

> I'm not sure it's safe to set it to true in db/config.cc in 5.4. Maybe based on the supported upgrade paths it is. But if it's not necessary we should stay on the safe side.

Wouldn't adding a note for that in the upgrade guide for this version be enough in this case?


IMO, having to rely on the `conf/scylla.yaml` template instead of the actual defaults looks a little inconvenient, specially for automating the deploy of new clusters and also because `conf/scylla.yaml` is very verbose. Having different values in `db/config.cc` and `conf/scylla.yaml` also doesn't make a lot of sense to me.

**Comment by kbr-scylla** [comment]
> But then what's the point of having consistent_cluster_management set to true by default in db/config.cc? 

To make the cluster automatically switch to Raft by default on upgrades.

> Shouldn't this value always be compatible with the value set in force_schema_commit_log?

If the cluster is upgraded correctly, the error won't be thrown, because SCHEMA_COMMITLOG cluster feature was enabled by the cluster earlier, so `force_schema_commit_log` is ignored.

If a new cluster is started, `force_schema_commit_log: true` needs to be provided from conf/scylla.yaml. (or through commandline)

If cluster is upgraded incorrectly, like from a version without SCHEMA_COMMITLOG feature, then it's good we set `force_schema_commit_log: false`, it serves as a protection from entering unsafe state.

> Wouldn't adding a note for that in the upgrade guide for this version be enough in this case?

What note? `force_schema_commit_log` is a value that if not set correctly, will cause the node to enter unsafe state. I think it's better pick a safe value and exit with an error if the user makes a mistake, and then it's easy for the user to correct the mistake, than pick unsafe value by default, and then if the user makes a mistake, the node enters unsafe state.

**Comment by vladzcloudius** [comment]
> IIUC The documented new cluster deployment procedure is using conf/scylla.yaml provided with the package. 

No, it is not.
There is no mention nor assumption whatsoever in our Docs (nor it should be) about having to use the `scylla.yaml` as some template: https://opensource.docs.scylladb.com/stable/getting-started/install-scylla/install-on-linux.html#configure-and-run-scylladb

The assumption that customers are going to or have to use anything from packaged scylla.yaml is completely baseless, @kbr-scylla.

This file is not a template - it's a example and is used by our customers as such.
Nor anything in scylla.yaml is supposed to be designed as some sort of a default as you suggest above, Kamil.

Note that scylla doesn't have to have ANY YAML configuration file - every parameter it gets can and many times is provided via the command line.

Scylla on the other hand is supposed to have sane defaults (defined in db/config.cc) for parameters that do have defaults so that it is able to boot up relying of these defaults.

And this is currently broken and **this** is what this GH issue us about!

About the issue you were trying to workaround (https://github.com/scylladb/scylladb/issues/16427#issuecomment-1860256186) - putting anything in the packaged scylla.yaml is **not** the way to resolve this for reasons I mentioned above.

There are many ways to do it. The one I would recommend is to make the definition of a "dangerous state" part of the scylla application state and make sure that you don't enable something you know is dangerous.

We have all the infrastructure needed to accomplish that (a.k.a. "FEATURES", see `supported_features` at `system.peers` table).

cc @asias @tgrabiec 

Please, let me know if the above makes sense, Kamil?

**Comment by kostja** [comment]
my take: @vladzcloudius is right, flip the default to true in 5.4

**Comment by kbr-scylla** [comment]
> There are many ways to do it. The one I would recommend is to make the definition of a "dangerous state" part of the scylla application state and make sure that you don't enable something you know is dangerous.

> We have all the infrastructure needed to accomplish that (a.k.a. "FEATURES", see supported_features in system.peers table).

@vladzcloudius there is a cluster feature for schema commitlog, but there is also a way to "force enable" schema commitlog regardless of the feature, that's what `force_schema_commit_log: true` does. The reason for it is because in new clusters that support schema commitlog, we want a newly booted node to start using schema commitlog *before* it can communicate with the cluster and synchronize cluster features. And precisely because it skips checking the cluster feature, it relies on the administrator for safety.

(This is my understanding -- @tgrabiec introduced schema commitlog and the `force_schema_commit_log` option, so he may correct me if I'm wrong)

Please let me know if it makes sense, Vlad.

---

> In my opinion, @vladzcloudius is right, flip the default in db/config.cc to true in 5.4

It's not a solution to the problem we see here. The problem is that there's a clear discrepancy in understanding of conf/scylla.yaml between core devs and ops/fields.

We in core assumed that whatever new default appears in conf/scylla.yaml will automatically appear in new clusters. This was done first for `force_schema_commit_log` and then for `consistent_cluster_management`. Maybe earlier for some other options  as well.

People who believed this assumption include me, @kostja, @avikivity, @mykaul, @tgrabiec and others. I know because we clearly made it when discussing the issue of enabling Raft in new 5.2 clusters on our status meetings.

And then it turns out this assumption is not true. Let me list the consequences if they are not immediately obvious:
- contrary to our (core devs) belief, new 5.1 and 5.2 and 5.4 clusters -- and corresponding enterprise versions -- were *not* enabled with schema commitlog from the start.
- contrary to our beliefs, new 5.2 and 5.4 clusters and corresponding enterprise versions are *not* using Raft by default.

This is very bad. It shows a clear hole in our processes and needs to be fixed somewhere above core development, on the management level. Flipping any option in db/config.cc to true or false will not fix the problem, it will just swipe it under the rug.

**Comment by tarzanek** [comment]
I think this weird dependency has to be unbound somehow

and no automation (neither ours nor anyone elses out there) is using newest conf/scylla.yaml - so you cannot assume people will use package delivered config file - rather than that they put there just the minimum options needed for Scylla to start and depend on default set in Scylla (and not in conf file)

even master dropped `force_schema_commit_log` now - so is master fixed re above?
https://github.com/scylladb/scylladb/pull/16254 makes the config.cc looks like Igors test, but works (per https://github.com/scylladb/scylladb/blob/master/db/config.cc#L1098 it is false, but we ignore it and internally set it to true anyways :-) )
- but I expect this cannot be backported, can it?

**Comment by kbr-scylla** [comment]
Yes `master` is fixed, the option is gone (ignored) in 5.5/6.0, but the reasoning that proves it's safe to remove the option in 5.5/6.0 cannot be applied to 5.4 I think, so it cannot be backported.

I don't think anything can / should be done in Scylla code at this point, we can only instruct users/customers to use `force_schema_commit_log: true` in conf/scylla.yaml (or pass through commandline) **in new 5.4 clusters** (not in upgraded ones!) That was the initial intention anyway IIUC.

And we still need to fix our processes.

**Comment by BlackMetalz** [comment]
Ubuntu 22.04
```
scylla-server                   5.4.1-0.20231231.3d22f42cf9c3-1
```

Can not start even with config defined in `/etc/scylla/scylla.yaml`
```
consistent_cluster_management: true
force_schema_commitlog: true
```

Log still the same `configuration: consistent_cluster_management requires schema commit log to be enabled`

**Comment by kbr-scylla** [comment]
@BlackMetalz it's `force_schema_commit_log` not `force_schema_commitlog`

**Comment by BlackMetalz** [comment]
> @BlackMetalz it's `force_schema_commit_log` not `force_schema_commitlog`

Ty for the quick response and it works!
But again, the log isn't clear or doesn't point to what needs to be done which could lead to bad configuration xD
```
[shard 0:main] init - Bad configuration: consistent_cluster_management requires schema commit log to be enabled
[shard 0:main] init - Startup failed: bad_configuration_error (std::exception)
```

Better log:
```
[shard 0:main] init - Bad configuration: consistent_cluster_management requires force_schema_commit_log to be enabled
```

**Comment by tzach** [comment]
This issue breaks many of the docker examples in scylla university and elsewhere. Please prioritize

**Comment by mykaul** [comment]
> This issue breaks many of the docker examples in scylla university and elsewhere. Please prioritize

@tzach - please see https://github.com/scylladb/scylladb/issues/16427#issuecomment-1874165269
