### ISSUE TITLE
data loss demostrated in python-driver tests

### ISSUE THREAD

**Issue by haarcuba** [scylladb/scylladb#1700]
# data loss when using query paging; demostrated in python-driver tests

Scylla version (or git commit hash): f92bbc6f44fc15445d6513ee524d0c56c26562c4

When running the `python-driver` integration test

```
tests/integration/standard/test_query_paging.py:QueryPagingTests.test_paging_state
```

Sometimes data is lost when retrieving the last page.

For your convinience I forked the [python-driver](https://github.com/haarcuba/python-driver) and hacked it to run a Scylla based CCM, provided you are using `scylla-ccm`. Checkout the [`test_paging_state`](https://github.com/haarcuba/python-driver/releases/tag/test_paging_state) tag.

The bug does not _always_ reproduce, so here is a shell script that runs in until failure (it takes less than 10 iterations usually)

```
#!/bin/sh
NUMBER_OF_ITERATIONS=$1
export PROTOCOL_VERSION=3

for i in $(seq 1 $NUMBER_OF_ITERATIONS); do
    echo GO ATTEMPT $i
    if (! nosetests --nologcapture -s tests/integration/standard/test_query_paging.py:QueryPagingTests.test_paging_state); then
        echo FAIL AT ATTEMPT $i
        exit -1;
    fi
    echo PASS AT ATTEMPT $i
done
```

A sample run (NOTE the use of `SCYLLA_CCM` to activate the hack):

```
fedora@ip-172-31-7-64 $ SCYLLA_CCM=yes ./go.sh 10 # run 10 attempts

.......
GO ATTEMPT 3
2016-09-25 14:54:15,854 INFO [__init__:53]: *** will use SCYLLA CCM instead of Cassandra ***
2016-09-25 14:54:15,857 WARNING [__init__:333]: IOError: [Errno 2] No such file or directory: '/home/fedora/python-driver/tests/integration/ccm/test_cluster/cluster.conf' Backtrace: [('/home/fedora/python-driver/tests/integration/__init__.py', 327, 'use_cluster', 'CCM_CLUSTER = CCMClusterFactory.load(path, cluster_name)'), ('/home/fedora/scylla-ccm/ccmlib/cluster_factory.py', 19, 'load', "with open(filename, 'r') as f:")]
2016-09-25 14:54:15,857 DEBUG [__init__:336]: Creating new CCM cluster, test_cluster, with args {'install_dir': '/home/fedora/scylla'}
2016-09-25 14:54:16,173 DEBUG [__init__:361]: Starting CCM cluster: test_cluster
2016-09-25 14:54:39,059 DEBUG [__init__:239]: Node node1 is up and listening 
2016-09-25 14:54:39,059 DEBUG [__init__:239]: Node node3 is up and listening 
2016-09-25 14:54:39,060 DEBUG [__init__:239]: Node node2 is up and listening 
2016-09-25 14:54:49,071 DEBUG [cluster:1166]: Connecting to cluster, contact points: ['127.0.0.1']; protocol version: 3
2016-09-25 14:54:49,072 DEBUG [asyncorereactor:196]: Validated loop dispatch with cassandra.io.asyncorereactor._AsyncorePipeDispatcher
2016-09-25 14:54:49,073 DEBUG [pool:137]: Host 127.0.0.1 is now marked up
2016-09-25 14:54:49,073 DEBUG [cluster:2641]: [control connection] Opening new connection to 127.0.0.1
2016-09-25 14:54:49,074 DEBUG [connection:625]: Not sending options message for new connection(140113610879504) to 127.0.0.1 because compression is disabled and a cql version was not specified
2016-09-25 14:54:49,074 DEBUG [connection:698]: Sending StartupMessage on <AsyncoreConnection(140113610879504) 127.0.0.1:9042>
2016-09-25 14:54:49,074 DEBUG [connection:704]: Sent StartupMessage on <AsyncoreConnection(140113610879504) 127.0.0.1:9042>
2016-09-25 14:54:49,075 DEBUG [asyncorereactor:226]: Starting asyncore event loop
2016-09-25 14:54:49,077 DEBUG [connection:711]: Got ReadyMessage on new connection (140113610879504) from 127.0.0.1
2016-09-25 14:54:49,078 DEBUG [cluster:2655]: [control connection] Established new connection <AsyncoreConnection(140113610879504) 127.0.0.1:9042>, registering watchers and refreshing schema and topology
2016-09-25 14:54:49,095 DEBUG [cluster:2799]: [control connection] Refreshing node list and token map using preloaded results
2016-09-25 14:54:49,096 INFO [policies:283]: Using datacenter 'dc1' for DCAwareRoundRobinPolicy (via host '127.0.0.1'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
2016-09-25 14:54:49,096 DEBUG [cluster:2868]: [control connection] Found new host to connect to: 127.0.0.3
2016-09-25 14:54:49,096 INFO [cluster:1536]: New Cassandra host <Host: 127.0.0.3 dc1> discovered
2016-09-25 14:54:49,096 DEBUG [cluster:1441]: Handling new host <Host: 127.0.0.3 dc1> and notifying listeners
2016-09-25 14:54:49,096 DEBUG [cluster:1446]: Done preparing queries for new host <Host: 127.0.0.3 dc1>
2016-09-25 14:54:49,096 DEBUG [pool:137]: Host 127.0.0.3 is now marked up
2016-09-25 14:54:49,097 DEBUG [cluster:2868]: [control connection] Found new host to connect to: 127.0.0.2
2016-09-25 14:54:49,097 INFO [cluster:1536]: New Cassandra host <Host: 127.0.0.2 dc1> discovered
2016-09-25 14:54:49,097 DEBUG [cluster:1441]: Handling new host <Host: 127.0.0.2 dc1> and notifying listeners
2016-09-25 14:54:49,097 DEBUG [cluster:1446]: Done preparing queries for new host <Host: 127.0.0.2 dc1>
2016-09-25 14:54:49,097 DEBUG [pool:137]: Host 127.0.0.2 is now marked up
2016-09-25 14:54:49,097 DEBUG [cluster:2888]: [control connection] Finished fetching ring info
2016-09-25 14:54:49,098 DEBUG [cluster:2890]: [control connection] Rebuilding token map due to topology changes
2016-09-25 14:54:49,131 DEBUG [metadata:2058]: user functions table not found
2016-09-25 14:54:49,131 DEBUG [metadata:2067]: user aggregates table not found
2016-09-25 14:54:49,145 DEBUG [cluster:1188]: Control connection created
2016-09-25 14:54:49,146 DEBUG [pool:328]: Initializing connection for host 127.0.0.3
2016-09-25 14:54:49,147 DEBUG [connection:625]: Not sending options message for new connection(140113593793040) to 127.0.0.3 because compression is disabled and a cql version was not specified
2016-09-25 14:54:49,147 DEBUG [pool:328]: Initializing connection for host 127.0.0.2
2016-09-25 14:54:49,148 DEBUG [connection:625]: Not sending options message for new connection(140113610984976) to 127.0.0.2 because compression is disabled and a cql version was not specified
2016-09-25 14:54:49,148 DEBUG [connection:698]: Sending StartupMessage on <AsyncoreConnection(140113610984976) 127.0.0.2:9042>
2016-09-25 14:54:49,148 DEBUG [connection:704]: Sent StartupMessage on <AsyncoreConnection(140113610984976) 127.0.0.2:9042>
2016-09-25 14:54:49,147 DEBUG [connection:698]: Sending StartupMessage on <AsyncoreConnection(140113593793040) 127.0.0.3:9042>
2016-09-25 14:54:49,150 DEBUG [connection:711]: Got ReadyMessage on new connection (140113610984976) from 127.0.0.2
2016-09-25 14:54:49,150 DEBUG [pool:333]: Finished initializing connection for host 127.0.0.2
2016-09-25 14:54:49,150 DEBUG [cluster:2338]: Added pool for host 127.0.0.2 to session
2016-09-25 14:54:49,150 DEBUG [connection:704]: Sent StartupMessage on <AsyncoreConnection(140113593793040) 127.0.0.3:9042>
2016-09-25 14:54:49,151 DEBUG [pool:328]: Initializing connection for host 127.0.0.1
2016-09-25 14:54:49,152 DEBUG [connection:625]: Not sending options message for new connection(140113593745488) to 127.0.0.1 because compression is disabled and a cql version was not specified
2016-09-25 14:54:49,152 DEBUG [connection:711]: Got ReadyMessage on new connection (140113593793040) from 127.0.0.3
2016-09-25 14:54:49,153 DEBUG [pool:333]: Finished initializing connection for host 127.0.0.3
2016-09-25 14:54:49,153 DEBUG [cluster:2338]: Added pool for host 127.0.0.3 to session
2016-09-25 14:54:49,153 DEBUG [connection:698]: Sending StartupMessage on <AsyncoreConnection(140113593745488) 127.0.0.1:9042>
2016-09-25 14:54:49,154 DEBUG [connection:704]: Sent StartupMessage on <AsyncoreConnection(140113593745488) 127.0.0.1:9042>
2016-09-25 14:54:49,154 DEBUG [connection:711]: Got ReadyMessage on new connection (140113593745488) from 127.0.0.1
2016-09-25 14:54:49,155 DEBUG [pool:333]: Finished initializing connection for host 127.0.0.1
2016-09-25 14:54:49,155 DEBUG [cluster:2338]: Added pool for host 127.0.0.1 to session
2016-09-25 14:54:49,219 DEBUG [cluster:3207]: Refreshing schema in response to schema change. {'keyspace': u'test3rf', 'change_type': u'CREATED', 'target_type': u'KEYSPACE'}
2016-09-25 14:54:49,219 DEBUG [cluster:2994]: [control connection] Waiting for schema agreement
2016-09-25 14:54:49,228 DEBUG [connection:445]: Message pushed from server: <EventMessage(event_type=u'SCHEMA_CHANGE', trace_id=None, event_args={'keyspace': u'test3rf', 'change_type': u'CREATED', 'target_type': u'KEYSPACE'}, stream_id=-1)>
2016-09-25 14:54:49,236 DEBUG [cluster:3022]: [control connection] Schemas mismatched, trying again
2016-09-25 14:54:49,438 DEBUG [cluster:3022]: [control connection] Schemas mismatched, trying again
2016-09-25 14:54:49,640 DEBUG [cluster:3022]: [control connection] Schemas mismatched, trying again
2016-09-25 14:54:49,842 DEBUG [cluster:3049]: [control connection] Schemas match
2016-09-25 14:54:49,905 DEBUG [connection:445]: Message pushed from server: <EventMessage(event_type=u'SCHEMA_CHANGE', trace_id=None, event_args={'keyspace': u'test2rf', 'change_type': u'CREATED', 'target_type': u'KEYSPACE'}, stream_id=-1)>
2016-09-25 14:54:49,919 DEBUG [cluster:3207]: Refreshing schema in response to schema change. {'keyspace': u'test2rf', 'change_type': u'CREATED', 'target_type': u'KEYSPACE'}
2016-09-25 14:54:49,920 DEBUG [cluster:2994]: [control connection] Waiting for schema agreement
2016-09-25 14:54:49,921 DEBUG [cluster:3022]: [control connection] Schemas mismatched, trying again
2016-09-25 14:54:50,123 DEBUG [cluster:3022]: [control connection] Schemas mismatched, trying again
2016-09-25 14:54:50,325 DEBUG [cluster:3022]: [control connection] Schemas mismatched, trying again
2016-09-25 14:54:50,527 DEBUG [cluster:3049]: [control connection] Schemas match
2016-09-25 14:54:50,596 DEBUG [connection:445]: Message pushed from server: <EventMessage(event_type=u'SCHEMA_CHANGE', trace_id=None, event_args={'keyspace': u'test1rf', 'change_type': u'CREATED', 'target_type': u'KEYSPACE'}, stream_id=-1)>
2016-09-25 14:54:50,598 DEBUG [cluster:3207]: Refreshing schema in response to schema change. {'keyspace': u'test1rf', 'change_type': u'CREATED', 'target_type': u'KEYSPACE'}
2016-09-25 14:54:50,599 DEBUG [cluster:2994]: [control connection] Waiting for schema agreement
2016-09-25 14:54:50,600 DEBUG [cluster:3022]: [control connection] Schemas mismatched, trying again
2016-09-25 14:54:50,804 DEBUG [cluster:3022]: [control connection] Schemas mismatched, trying again
2016-09-25 14:54:51,009 DEBUG [cluster:3022]: [control connection] Schemas mismatched, trying again
2016-09-25 14:54:51,213 DEBUG [cluster:3022]: [control connection] Schemas mismatched, trying again
2016-09-25 14:54:51,415 DEBUG [cluster:3022]: [control connection] Schemas mismatched, trying again
2016-09-25 14:54:51,619 DEBUG [cluster:3049]: [control connection] Schemas match
2016-09-25 14:54:51,620 DEBUG [cluster:2994]: [control connection] Waiting for schema agreement
2016-09-25 14:54:51,623 DEBUG [cluster:3049]: [control connection] Schemas match
2016-09-25 14:54:51,624 DEBUG [cluster:2994]: [control connection] Waiting for schema agreement
2016-09-25 14:54:51,632 DEBUG [cluster:3049]: [control connection] Schemas match
2016-09-25 14:54:51,634 DEBUG [cluster:2994]: [control connection] Waiting for schema agreement
2016-09-25 14:54:51,638 DEBUG [cluster:3049]: [control connection] Schemas match
2016-09-25 14:54:51,763 DEBUG [cluster:3207]: Refreshing schema in response to schema change. {'keyspace': u'test3rf', 'change_type': u'CREATED', 'target_type': u'TABLE', u'table': u'test'}
2016-09-25 14:54:51,763 DEBUG [cluster:2994]: [control connection] Waiting for schema agreement
2016-09-25 14:54:51,779 DEBUG [cluster:3022]: [control connection] Schemas mismatched, trying again
2016-09-25 14:54:51,796 DEBUG [connection:445]: Message pushed from server: <EventMessage(event_type=u'SCHEMA_CHANGE', trace_id=None, event_args={'keyspace': u'test3rf', 'change_type': u'CREATED', 'target_type': u'TABLE', u'table': u'test'}, stream_id=-1)>
2016-09-25 14:54:51,983 DEBUG [cluster:3022]: [control connection] Schemas mismatched, trying again
2016-09-25 14:54:52,187 DEBUG [cluster:3022]: [control connection] Schemas mismatched, trying again
2016-09-25 14:54:52,389 DEBUG [cluster:3022]: [control connection] Schemas mismatched, trying again
2016-09-25 14:54:52,593 DEBUG [cluster:3049]: [control connection] Schemas match
2016-09-25 14:54:52,619 DEBUG [cluster:3144]: Shutting down Cluster Scheduler
2016-09-25 14:54:52,698 DEBUG [cluster:2747]: Shutting down control connection
2016-09-25 14:54:52,699 DEBUG [asyncorereactor:316]: Closing connection (140113610879504) to 127.0.0.1
2016-09-25 14:54:52,699 DEBUG [asyncorereactor:320]: Closed socket to 127.0.0.1
2016-09-25 14:54:52,699 DEBUG [asyncorereactor:316]: Closing connection (140113593793040) to 127.0.0.3
2016-09-25 14:54:52,699 DEBUG [asyncorereactor:320]: Closed socket to 127.0.0.3
2016-09-25 14:54:52,700 DEBUG [asyncorereactor:316]: Closing connection (140113610984976) to 127.0.0.2
2016-09-25 14:54:52,700 DEBUG [asyncorereactor:320]: Closed socket to 127.0.0.2
2016-09-25 14:54:52,700 DEBUG [asyncorereactor:316]: Closing connection (140113593745488) to 127.0.0.1
2016-09-25 14:54:52,701 DEBUG [asyncorereactor:320]: Closed socket to 127.0.0.1
2016-09-25 14:54:52,703 DEBUG [cluster:1166]: Connecting to cluster, contact points: ['127.0.0.1']; protocol version: 3
2016-09-25 14:54:52,703 DEBUG [pool:137]: Host 127.0.0.1 is now marked up
2016-09-25 14:54:52,703 DEBUG [cluster:2641]: [control connection] Opening new connection to 127.0.0.1
2016-09-25 14:54:52,704 DEBUG [connection:625]: Not sending options message for new connection(140113593746512) to 127.0.0.1 because compression is disabled and a cql version was not specified
2016-09-25 14:54:52,704 DEBUG [connection:698]: Sending StartupMessage on <AsyncoreConnection(140113593746512) 127.0.0.1:9042>
2016-09-25 14:54:52,704 DEBUG [connection:704]: Sent StartupMessage on <AsyncoreConnection(140113593746512) 127.0.0.1:9042>
2016-09-25 14:54:52,705 DEBUG [connection:711]: Got ReadyMessage on new connection (140113593746512) from 127.0.0.1
2016-09-25 14:54:52,706 DEBUG [cluster:2655]: [control connection] Established new connection <AsyncoreConnection(140113593746512) 127.0.0.1:9042>, registering watchers and refreshing schema and topology
2016-09-25 14:54:52,715 DEBUG [cluster:2799]: [control connection] Refreshing node list and token map using preloaded results
2016-09-25 14:54:52,716 INFO [policies:283]: Using datacenter 'dc1' for DCAwareRoundRobinPolicy (via host '127.0.0.1'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
2016-09-25 14:54:52,716 DEBUG [cluster:2868]: [control connection] Found new host to connect to: 127.0.0.3
2016-09-25 14:54:52,716 INFO [cluster:1536]: New Cassandra host <Host: 127.0.0.3 dc1> discovered
2016-09-25 14:54:52,716 DEBUG [cluster:1441]: Handling new host <Host: 127.0.0.3 dc1> and notifying listeners
2016-09-25 14:54:52,717 DEBUG [cluster:1446]: Done preparing queries for new host <Host: 127.0.0.3 dc1>
2016-09-25 14:54:52,717 DEBUG [pool:137]: Host 127.0.0.3 is now marked up
2016-09-25 14:54:52,717 DEBUG [cluster:2868]: [control connection] Found new host to connect to: 127.0.0.2
2016-09-25 14:54:52,717 INFO [cluster:1536]: New Cassandra host <Host: 127.0.0.2 dc1> discovered
2016-09-25 14:54:52,717 DEBUG [cluster:1441]: Handling new host <Host: 127.0.0.2 dc1> and notifying listeners
2016-09-25 14:54:52,717 DEBUG [cluster:1446]: Done preparing queries for new host <Host: 127.0.0.2 dc1>
2016-09-25 14:54:52,717 DEBUG [pool:137]: Host 127.0.0.2 is now marked up
2016-09-25 14:54:52,718 DEBUG [cluster:2888]: [control connection] Finished fetching ring info
2016-09-25 14:54:52,718 DEBUG [cluster:2890]: [control connection] Rebuilding token map due to topology changes
2016-09-25 14:54:52,734 DEBUG [metadata:2058]: user functions table not found
2016-09-25 14:54:52,734 DEBUG [metadata:2067]: user aggregates table not found
2016-09-25 14:54:52,747 DEBUG [cluster:1188]: Control connection created
2016-09-25 14:54:52,748 DEBUG [pool:328]: Initializing connection for host 127.0.0.3
2016-09-25 14:54:52,752 DEBUG [pool:328]: Initializing connection for host 127.0.0.2
2016-09-25 14:54:52,753 DEBUG [connection:625]: Not sending options message for new connection(140113593629776) to 127.0.0.3 because compression is disabled and a cql version was not specified
2016-09-25 14:54:52,754 DEBUG [connection:625]: Not sending options message for new connection(140113584812560) to 127.0.0.2 because compression is disabled and a cql version was not specified
2016-09-25 14:54:52,754 DEBUG [connection:698]: Sending StartupMessage on <AsyncoreConnection(140113593629776) 127.0.0.3:9042>
2016-09-25 14:54:52,754 DEBUG [connection:704]: Sent StartupMessage on <AsyncoreConnection(140113593629776) 127.0.0.3:9042>
2016-09-25 14:54:52,754 DEBUG [connection:698]: Sending StartupMessage on <AsyncoreConnection(140113584812560) 127.0.0.2:9042>
2016-09-25 14:54:52,755 DEBUG [connection:711]: Got ReadyMessage on new connection (140113593629776) from 127.0.0.3
2016-09-25 14:54:52,755 DEBUG [connection:704]: Sent StartupMessage on <AsyncoreConnection(140113584812560) 127.0.0.2:9042>
2016-09-25 14:54:52,756 DEBUG [pool:333]: Finished initializing connection for host 127.0.0.3
2016-09-25 14:54:52,756 DEBUG [cluster:2338]: Added pool for host 127.0.0.3 to session
2016-09-25 14:54:52,756 DEBUG [pool:328]: Initializing connection for host 127.0.0.1
2016-09-25 14:54:52,757 DEBUG [connection:711]: Got ReadyMessage on new connection (140113584812560) from 127.0.0.2
2016-09-25 14:54:52,757 DEBUG [connection:625]: Not sending options message for new connection(140113593561424) to 127.0.0.1 because compression is disabled and a cql version was not specified
2016-09-25 14:54:52,758 DEBUG [connection:698]: Sending StartupMessage on <AsyncoreConnection(140113593561424) 127.0.0.1:9042>
2016-09-25 14:54:52,758 DEBUG [connection:704]: Sent StartupMessage on <AsyncoreConnection(140113593561424) 127.0.0.1:9042>
2016-09-25 14:54:52,759 DEBUG [pool:333]: Finished initializing connection for host 127.0.0.2
2016-09-25 14:54:52,759 DEBUG [connection:711]: Got ReadyMessage on new connection (140113593561424) from 127.0.0.1
2016-09-25 14:54:52,759 DEBUG [cluster:2338]: Added pool for host 127.0.0.2 to session
2016-09-25 14:54:52,760 DEBUG [pool:333]: Finished initializing connection for host 127.0.0.1
2016-09-25 14:54:52,760 DEBUG [cluster:2338]: Added pool for host 127.0.0.1 to session
2016-09-25 14:54:53,016 DEBUG [cluster:3144]: Shutting down Cluster Scheduler
2016-09-25 14:54:53,016 DEBUG [cluster:2747]: Shutting down control connection
2016-09-25 14:54:53,016 DEBUG [asyncorereactor:316]: Closing connection (140113593746512) to 127.0.0.1
2016-09-25 14:54:53,016 DEBUG [asyncorereactor:320]: Closed socket to 127.0.0.1
2016-09-25 14:54:53,016 DEBUG [asyncorereactor:316]: Closing connection (140113593629776) to 127.0.0.3
2016-09-25 14:54:53,016 DEBUG [asyncorereactor:320]: Closed socket to 127.0.0.3
2016-09-25 14:54:53,017 DEBUG [asyncorereactor:316]: Closing connection (140113584812560) to 127.0.0.2
2016-09-25 14:54:53,017 DEBUG [asyncorereactor:320]: Closed socket to 127.0.0.2
2016-09-25 14:54:53,017 DEBUG [asyncorereactor:316]: Closing connection (140113593561424) to 127.0.0.1
2016-09-25 14:54:53,018 DEBUG [asyncorereactor:320]: Closed socket to 127.0.0.1
F2016-09-25 14:54:53,019 DEBUG [__init__:283]: Removing cluster test_cluster
2016-09-25 14:54:53,392 WARNING [__init__:396]: Did not find cluster: test_cluster
2016-09-25 14:54:53,392 WARNING [__init__:396]: Did not find cluster: multidc_test_cluster

======================================================================
FAIL: Test to validate paging state api
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fedora/python-driver/tests/integration/standard/test_query_paging.py", line 98, in test_paging_state
    self.assertEqual(len(list_all_results), 100)
AssertionError: 97 != 100

----------------------------------------------------------------------
Ran 1 test in 37.535s

FAILED (failures=1)
2016-09-25 14:54:53,393 DEBUG [asyncorereactor:247]: Waiting for event loop thread to join...
2016-09-25 14:54:53,469 DEBUG [asyncorereactor:237]: Asyncore event loop ended
2016-09-25 14:54:53,507 DEBUG [asyncorereactor:254]: Event loop thread was joined
FAIL AT ATTEMPT 3
```

**Comment by penberg** [comment]
@tgrabiec @elcallio @pdziepak

**Comment by slivne** [comment]
@lmr - we started running this on jenkins can you please check if you can find this test (and if not why) and lets see if it passes. We have fixed a few bugs related to paging and this may have been fixed.

**Comment by haarcuba** [comment]
update: @lmr @slivne this *test* only appears after python-driver version 3.7.0, so currently it is not covered by the jenkins job. You can still reproduce it with Scylla using my original instructions in this issue.

**Comment by lmr** [comment]
@haarcuba, I have updated monster to run cassandra-driver 3.7.1, so we should start seeing this problem.

**Comment by elcallio** [comment]
Not sure why I am assigned this, but beyond issues with python driver, it is quite possible that this was related to (and fixed by) 20493033991dda74bcf88c5f4ccd6057baeebb19

If so, please close.

**Comment by penberg** [comment]
We're now running Python driver tests on Jenkins. @larisau, can we close this issue?

**Comment by larisau** [comment]
Yes, it's running on jenkins, but it still happens :( 
This is the run from July 24:
http://jenkins.cloudius-systems.com:8080/view/scylla-master/job/scylla-master-python-driver-matrix/53/label=godzilla,mode=release/testReport/junit/version_3.9.0_v3_tests.integration.standard.test_query_paging/QueryPagingTests/test_paging_state/

**Comment by penberg** [comment]
OK, let's keep the issue open then. Thanks for the update, @larisau!

**Comment by duarten** [comment]
Is this still failing?

**Comment by bentsi** [comment]
Yes: https://jenkins.scylladb.com/job/scylla-master/job/python-driver-matrix-test/263/testReport/version_3.9.0_v3_tests.integration.standard.test_query_paging/QueryPagingTests/test_paging_state/

**Comment by kostja** [comment]
@avelanarius is the test still failing? If not, let's close it. If yes, could you please clarify, is it a server-side or a client-side (driver) bug?

**Comment by kostja** [comment]
@avelanarius I presume it's too old/irrelevant.
