### ISSUE TITLE
test_lwt.py::test_no_cross_shard_ops fails with tablets

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#17045]
https://jenkins.scylladb.com/job/scylla-master/job/byo/job/dtest-byo/119

scylla-release: 0.20240125.03313d359e32
scylla-version: 5.5.0~dev
scylla-x86_64-BuildID[sha1]: 3ba319c2856389fd41198911105d86848352105e

`FAILED lwt_test.py::TestLwt::test_no_cross_shard_ops`

```
[2024-01-26T16:07:37.245Z] >       assert after.get(name, 0) - before.get(name, 0) <= 16, f"{before}:{after}"
[2024-01-26T16:07:37.245Z] E       AssertionError: {'scylla_storage_proxy_replica_cross_shard_ops.*(statement|main)': 72}:{'scylla_storage_proxy_replica_cross_shard_ops.*(statement|main)': 149}
[2024-01-26T16:07:37.245Z] E       assert (149 - 72) <= 16
[2024-01-26T16:07:37.245Z] E        +  where 149 = <built-in method get of dict object at 0x7fae6d3e7e40>('scylla_storage_proxy_replica_cross_shard_ops.*(statement|main)', 0)
[2024-01-26T16:07:37.245Z] E        +    where <built-in method get of dict object at 0x7fae6d3e7e40> = {'scylla_storage_proxy_replica_cross_shard_ops.*(statement|main)': 149}.get
[2024-01-26T16:07:37.245Z] E        +  and   72 = <built-in method get of dict object at 0x7fae6f255cc0>('scylla_storage_proxy_replica_cross_shard_ops.*(statement|main)', 0)
[2024-01-26T16:07:37.245Z] E        +    where <built-in method get of dict object at 0x7fae6f255cc0> = {'scylla_storage_proxy_replica_cross_shard_ops.*(statement|main)': 72}.get
```

**Comment by xemul** [comment]
Seems to be lack of ~~shard~~tablet-awareness from the driver used, so requests indeed got onto "wrong" shard and bounce

**Comment by mykaul** [comment]
I assume fixed by now. Please re-open if needed.

**Comment by kostja** [comment]
It's not fixed, but I am working on explicitly disabling tablets for this test, they don't make sense here.
