### ISSUE TITLE
offline-install fail on fetching nodes info from gossip

### ISSUE THREAD

**Issue by benipeled** [scylladb/scylladb#17412]
### Issue description

```
01:53:37  < t:2024-02-16 23:53:32,087 f:health_checker.py l:60   c:sdcm.utils.health_checker p:WARNING > Gossip info is not available. Search for the warning above
01:53:37  < t:2024-02-16 23:53:32,090 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2024-02-16 23:53:32.086: (ClusterHealthValidatorEvent Severity.ERROR) period_type=one-time event_id=5362e30d-0bab-4ed8-8a6f-e874b668c878: type=NodeSchemaVersion node=artifacts-ubuntu2204-jenkins-db-node-d978fb0d-0-1 error=Current node Node artifacts-ubuntu2204-jenkins-db-node-d978fb0d-0-1 [34.139.30.127 | 10.142.0.128] (seed: True). Node Node artifacts-ubuntu2204-jenkins-db-node-d978fb0d-0-1 [34.139.30.127 | 10.142.0.128] (seed: True) (not target node) exists in the nodetool.status but missed in gossip.
```

Seen on debian,ubuntu,rocky artifacts-offline-install tests

https://jenkins.scylladb.com/job/scylla-master/job/artifacts-offline-install/job/artifacts-ubuntu2204-nonroot-test/341
https://jenkins.scylladb.com/job/scylla-master/job/artifacts-offline-install/job/artifacts-ubuntu2204-nonroot-test/340
https://jenkins.scylladb.com/job/scylla-master/job/artifacts-offline-install/job/artifacts-rocky9-nonroot-test/141

I'm not sure if it's a real bug or a need for SCT-adjustment following recent core changes:

- https://github.com/scylladb/scylladb/pull/17317
- https://github.com/scylladb/scylladb/pull/17162

@fruch @denesb

**Comment by tchaikov** [comment]
> > < t:2024-02-16 23:54:50,312 f:cluster.py      l:2659 c:sdcm.cluster         p:DEBUG >   what():  Could not setup Async I/O: Resource temporarily unavailable. The required nr_event (1) exceeds the limit of request capacity in /proc/sys/fs/aio-max-nr (65536). Try increasing that number or reducing the amount of logical CPUs available for your application
> 
> I don't understand: how do we fail this check when we want 1 unit and have 65536 available? Maybe ScyllaDB took all those units and there is none left for the tools? Will we be hitting this in other prod environments? Should we use the `epoll` backend for tools? @avikivity

just wanted to confirm this. as we take all available aio slots if the `/proc/sys/fs/aio-max-nr` is not large enough, see https://github.com/scylladb/seastar/blob/9b8a9c605030bdc44c46b30b97e8004dc520cb57/src/core/reactor.cc#L4254-L4264 . but we do raise this setting to `30000000`, see https://github.com/scylladb/scylladb/blob/f83df24108851fa856bbc33e6d1e751d783ecdc2/dist/common/sysctl.d/99-scylla-aio.conf#L2 . so i think we should increase aio-nr also when performing artifact tests.

**Comment by tchaikov** [comment]
https://github.com/scylladb/scylla-cluster-tests/pull/7219 was created to implement this.

**Comment by denesb** [comment]
Thanks @tchaikov for getting to the bottom of this.

**Comment by fruch** [comment]
> [scylladb/scylla-cluster-tests#7219](https://github.com/scylladb/scylla-cluster-tests/pull/7219) was created to implement this.

@tchaikov I think it should also be mentioned in docs of offline installs, that the prerequisite has changed
also for docker related usage it should be updated, and also for scylla-operator docs that probably refer to those numbers.

**Comment by tchaikov** [comment]
@fruch i think it's more related to non-root mode installation.

because, to get scylla up and running with its maximum performance, we would need more settings than `fs.aio-max-nr`. the reason why we have this issue was that the test was performed in a non-root mode. so `install.sh` does not apply the setting on behalf of us. so, shall we encourage these non-root user to run `sudo sysctl -p dist/common/sysctl.d/*.conf` to enjoy the full power of scylla ?

**Comment by tchaikov** [comment]
@denesb hi Botond, how about adding a warning message in `install.sh` ? so that user is aware that he/she would run into a similar problem when running multiple scylla instances on a single machine without setting `fs.aio-max-nr` beforehand? this would be a typical use case after `scylla nodetool` is "mainstreamed".

**Comment by fruch** [comment]
> @fruch i think it's more related to non-root mode installation.
> 
> because, to max out the performance of scylla, we would need more settings than `fs.aio-max-nr`. the reason why we have this issue was that the test was performed in a non-root mode. so `install.sh` did not apply the setting on behalf of us. so, shall we encourage these non-root users to run `sudo sysctl -p dist/common/sysctl.d/*.conf` to enjoy the full power of scylla ?

I guess that's could be one of the options, I'm just saying it should be documented in some why

**Comment by tchaikov** [comment]
my thinking is that no document is the best document =) but if we have to, then surely we should add.

**Comment by fruch** [comment]
> my thinking is that no document is the best document =) but if we have to, then surely we should add.

see how many time in our public doc we mention tweaking this one (yeah most times is cause of running with docker)
https://www.google.com/search?q=aio-nr+scylladb

I just think: https://opensource.docs.scylladb.com/stable/getting-started/installation-common/unified-installer.html should mentiod it

**Comment by roydahan** [comment]
In a related issue @avikivity mentioned that if we couldn’t set the max-aio-nr it should fallback to epoll

**Comment by tchaikov** [comment]
hmm, if that's the case, we would have to update scylla-nodetool to try aio and fallback to epoll. we should not do this in seastar.

**Comment by denesb** [comment]
> hmm, if that's the case, we would have to update scylla-nodetool to try aio and fallback to epoll. we should not do this in seastar.

I don't think it is possible to "try" one backend and fall-back to the other. Not without seastar changes making this possible. Maybe we can just default to the epoll backend. We don't really care about performance with these tools, the epoll backend will be just fine. We just need to make sure it won't resort to busy polling, driving CPU usage to 100%.

**Comment by denesb** [comment]
PR here: https://github.com/scylladb/scylladb/pull/17438

**Comment by denesb** [comment]
> I don't understand - why this started happening now? Due to the move to the native implementation?

Yes, as we implement new commands and push fixed into scylla-nodetool, the `nodetool-wrapper` we commited to `scylla-tools-java` starts to forward more and more commands to the native implementation and we are finding some rough corners.

**Comment by fruch** [comment]
> I don't understand - why this started happening now? Due to the move to the native implementation? 

This specific command, that is used in those tests, is now implemented:
https://github.com/scylladb/scylladb/pull/17317

**Comment by denesb** [comment]
@mykaul after https://github.com/scylladb/scylladb/pull/17168 gets in, dtests will also start to use the native nodetool. Said PR currently serves as CI on fixing any remaining problems that surface when running dtest with the new nodetool.

**Comment by denesb** [comment]
I think we can consider this fixed by https://github.com/scylladb/scylladb/pull/17438.

**Comment by benipeled** [comment]
@denesb we still face this issue - nightly build https://jenkins.scylladb.com/job/scylla-master/job/artifacts-offline-install/job/artifacts-ubuntu2204-nonroot-test/357

**Comment by fruch** [comment]
> @denesb we still face this issue - nightly build https://jenkins.scylladb.com/job/scylla-master/job/artifacts-offline-install/job/artifacts-ubuntu2204-nonroot-test/357

@benipeled that looks like a whole different error, related to @denesb doing :)

SCT isn't happen with `nodetool info` output:
```
01:47:51    File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/cluster.py", line 4657, in wait_for_init
01:47:51      node_list[0].check_node_health()
01:47:51    File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/cluster.py", line 2591, in check_node_health
01:47:51      for event in events:
01:47:51    File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/utils/health_checker.py", line 275, in check_group0_tokenring_consistency
01:47:51      current_node.name, current_node.host_id)
01:47:51    File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/cluster.py", line 400, in host_id
01:47:51      return self.parent_cluster.get_nodetool_info(self, publish_event=False).get('ID')
01:47:51  AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by denesb** [comment]
Is this happening with current master?

**Comment by benipeled** [comment]
@fruch the artifacts-offline-install tests are still failing - is it a scylla issue? I recall something about SCT fix for parsing the nodetool output

https://jenkins.scylladb.com/job/scylla-master/job/artifacts-offline-install/job/artifacts-ubuntu2204-nonroot-test/365/consoleFull

**Comment by fruch** [comment]
> Is this happening with current master?

yes it's still happening

in those jobs offline jobs:

https://argus.scylladb.com/workspace?state=WyIwYmUwZTRkNi0yZGM2LTQ2YTQtYTkzOC1lYmVjZTRiNDI1YjEiLCJmOTNjZmFkYS1hMTRkLTQyMGYtYTdiNS04ZjQwZDlkZmRhYTciLCI4NmVlZjBhZS0zODUyLTRkNWQtYWI3OS02NWQyNWFhMzE0ZDIiLCIzM2QyYjNlYi05YmZhLTQ5MmUtODE2NC1kZTE5OGM1YzVmYWYiLCJkN2U0N2M2My0wMzgwLTQ0YjQtYmQyNS02ZWJjNjEzMjE3ODUiXQ

**Comment by fruch** [comment]
@tchaikov @denesb 
94dac43b2f4838cd4cb971c4c5815c91fa648fe4 didn't seems to have solved the issue

**Comment by denesb** [comment]
@benipeled @fruch I am looking at the latest failed job: https://jenkins.scylladb.com/job/scylla-master/job/artifacts-offline-install/job/artifacts-ubuntu2204-nonroot-test/379/consoleFull

And I cannot see any error related to nodetool. The error I see is:
```
   6 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING > Traceback (most recent call last):                                                                                                                                
   7 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >   File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/cluster.py", line 3812, in node_startup
   8 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >     cl_inst.node_startup(_node, **setup_kwargs)                                                                                                                   
   9 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >   File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/cluster.py", line 4634, in node_startup
  10 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >     self.log.debug('io.conf before reboot: %s', node.remoter.sudo('cat /etc/scylla.d/io.conf').stdout)                                                            
  11 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >   File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/remote/base.py", line 123, in sudo     
  12 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >     return self.run(cmd=cmd,                                                                                                                                      
  13 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >   File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in ru
     n                                                                                                                                                                                                                                                         
  14 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >     result = _run()                                                                                                                                               
  15 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >   File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 70, in inner
  16 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >     return func(*args, **kwargs)                                                                                                                                  
  17 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >   File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 605, in _r
     un                                                                                                                                                                                                                                                        
  18 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >     return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)                                                                         
  19 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >   File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _r
     un_execute                                                                                                                                                                                                                                                
  20 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >     result = connection.run(**command_kwargs)                                                                                                                     
  21 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >   File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", lin
     e 620, in run                                                                                                                                                                                                                                             
  22 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >     return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)                                                         
  23 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >   File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", lin
     e 655, in _complete_run                                                                                                                                                                                                                                   
  24 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >     raise UnexpectedExit(result)                                                                                                                                  
  25 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING > sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!                                                                        
  26 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >                                                                                                                                                                   
  27 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING > Command: 'sudo cat /etc/scylla.d/io.conf'                                                                                                                         
  28 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >                                                                                                                                                                   
  29 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING > Exit code: 1                                                                                                                                                      
  30 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >                                                                                                                                                                   
  31 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING > Stdout:                                                                                                                                                           
  32 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >                                                                                                                                                                   
  33 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >                                                                                                                                                                   
  34 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >                                                                                                                                                                   
  35 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING > Stderr:                                                                                                                                                           
  36 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >                                                                                                                                                                   
  37 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING > cat: /etc/scylla.d/io.conf: No such file or directory                                                                                                             
  38 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >                                                                                                                                                                   
  39 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >                                                                                                                                                                   
  40 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >                                                                                                                                                                   
  41 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >    
```

**Comment by fruch** [comment]
> @benipeled @fruch I am looking at the latest failed job: https://jenkins.scylladb.com/job/scylla-master/job/artifacts-offline-install/job/artifacts-ubuntu2204-nonroot-test/379/consoleFull
> 
> And I cannot see any error related to nodetool. The error I see is:
> 
> ```
>    6 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING > Traceback (most recent call last):                                                                                                                                
>    7 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >   File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/cluster.py", line 3812, in node_startup
>    8 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >     cl_inst.node_startup(_node, **setup_kwargs)                                                                                                                   
>    9 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >   File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/cluster.py", line 4634, in node_startup
>   10 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >     self.log.debug('io.conf before reboot: %s', node.remoter.sudo('cat /etc/scylla.d/io.conf').stdout)                                                            
>   11 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >   File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/remote/base.py", line 123, in sudo     
>   12 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >     return self.run(cmd=cmd,                                                                                                                                      
>   13 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >   File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 614, in ru
>      n                                                                                                                                                                                                                                                         
>   14 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >     result = _run()                                                                                                                                               
>   15 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >   File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 70, in inner
>   16 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >     return func(*args, **kwargs)                                                                                                                                  
>   17 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >   File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 605, in _r
>      un                                                                                                                                                                                                                                                        
>   18 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >     return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)                                                                         
>   19 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >   File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 538, in _r
>      un_execute                                                                                                                                                                                                                                                
>   20 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >     result = connection.run(**command_kwargs)                                                                                                                     
>   21 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >   File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", lin
>      e 620, in run                                                                                                                                                                                                                                             
>   22 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >     return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)                                                         
>   23 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >   File "/tmp/workspace/scylla-master/artifacts-offline-install/artifacts-ubuntu2204-nonroot-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", lin
>      e 655, in _complete_run                                                                                                                                                                                                                                   
>   24 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >     raise UnexpectedExit(result)                                                                                                                                  
>   25 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING > sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!                                                                        
>   26 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >                                                                                                                                                                   
>   27 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING > Command: 'sudo cat /etc/scylla.d/io.conf'                                                                                                                         
>   28 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >                                                                                                                                                                   
>   29 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING > Exit code: 1                                                                                                                                                      
>   30 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >                                                                                                                                                                   
>   31 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING > Stdout:                                                                                                                                                           
>   32 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >                                                                                                                                                                   
>   33 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >                                                                                                                                                                   
>   34 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >                                                                                                                                                                   
>   35 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING > Stderr:                                                                                                                                                           
>   36 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >                                                                                                                                                                   
>   37 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING > cat: /etc/scylla.d/io.conf: No such file or directory                                                                                                             
>   38 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >                                                                                                                                                                   
>   39 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >                                                                                                                                                                   
>   40 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >                                                                                                                                                                   
>   41 < t:2024-04-18 22:42:46,646 f:tester.py       l:603  c:ArtifactsTest        p:WARNING >    
> ```


@denesb 
this is different issue, that I've addressed in 
https://github.com/scylladb/scylla-cluster-tests/pull/7355

the actual issue is still happening, in my stagin job:
https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/artifacts-ubuntu2204-test/44/

we still can't run any nodetool commands on those setups

**Comment by fruch** [comment]
@denesb 

I'm marking it as a release blocker (i.e. we can't release 6.0 without clarifying this one)

**Comment by mykaul** [comment]
> we still can't run any nodetool commands on those setups

@fruch - what happens when you do?
(and btw, it only happens in offline install?)

**Comment by fruch** [comment]
> > we still can't run any nodetool commands on those setups
> 
> @fruch - what happens when you do? (and btw, it only happens in offline install?)

the command coredump, and doesn't execute anything.

yes it happens on offline installs only

**Comment by mykaul** [comment]
Do we have the coredump available? I remember earlier it was not produced.

**Comment by fruch** [comment]
the output is quite clear, I don't think a coredump is needed in this case:
```
terminate called after throwing an instance of 'std::runtime_error'
   what():  Could not setup Async I/O: Resource temporarily unavailable. The required nr_event (1) exceeds the limit of request capacity in /proc/sys/fs/aio-max-nr (65536). Try increasing that number or reducing the amount of logical CPUs available for your application
```

**Comment by denesb** [comment]
> the actual issue is still happening, in my stagin job: https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/artifacts-ubuntu2204-test/44/
> 
> we still can't run any nodetool commands on those setups

I again see a different error, I can't even see anything related to nodetool in the (full) logs:
```
12:55:19  < t:2024-04-21 09:55:18,650 f:decorators.py   l:75   c:sdcm.utils.decorators p:ERROR > '_wait_for_nodes_up_and_normal': Number of retries exceeded!
12:55:19  < t:2024-04-21 09:55:18,693 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > 2024-04-21 09:55:18.689: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=55cece59-4bb8-44ba-a677-70cbdc9032e4, source=ArtifactsTest.SetUp()
12:55:19  < t:2024-04-21 09:55:18,693 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:ERROR > exception=Not all nodes joined the cluster
```

Am I looking at the wrong logs?

**Comment by denesb** [comment]
I found the errors in the sct log file.

**Comment by denesb** [comment]
So a full error looks like this:
```
6528 < t:2024-04-21 09:51:42,210 f:remote_base.py  l:521  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/home/scylla-test/scylladb/share/cassandra/bin/nodetool  status "...                                                                             
   1 < t:2024-04-21 09:51:42,712 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > /home/scylla-test/scylladb/share/cassandra/bin/nodetool: line 40:  6056 Aborted                 (core dumped) "$SCYLLA_PATH" nodetool "$@" $help_opt &> /dev/null 
   2 < t:2024-04-21 09:51:43,213 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > terminate called after throwing an instance of 'std::runtime_error'                                                                                               
   3 < t:2024-04-21 09:51:43,713 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG >   what():  Could not setup Async I/O: Resource temporarily unavailable. The required nr_event (1) exceeds the limit of request capacity in /proc/sys/fs/aio-max-nr
      (65536). Try increasing that number or reducing the amount of logical CPUs available for your application 
```

This could also be an issue with the `nodetool-wrapper` script. There is an open PR to get rid of it: https://github.com/scylladb/scylladb/pull/18255.

**Comment by denesb** [comment]
The problem is that I cannot even see the exact command line. I checked and we don't even create a reactor instance when `--help` is used, or when an unknown command is passed (shouldn't be the case here). I don't understand what is going on here. A coredump would also help, but I don't see one.

@fruch would it be possibe to run this job with a custom ScyllaDB build?

**Comment by denesb** [comment]
> @fruch would it be possibe to run this job with a custom ScyllaDB build?

Nevermind, I found it.

**Comment by denesb** [comment]
I ran the job with https://github.com/scylladb/scylladb/pull/18255 and it passed: https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/artifacts-ubuntu2204-test/45/
