### ISSUE TITLE
docs: Issue on page Consistency Level Calculator

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#18606]
I would like to report an issue on page https://opensource.docs.scylladb.com/branch-5.4/cql/consistency-calculator

### Problem

How is it possible that e.g, with Nodes=3, RF=3,
- READ_CL=QUORUM, WRITE_CL=QUORUM guarantees consistent reads, while
- READ_CL=ALL, WRITE_CL=QUORUM guarantees only eventually consistent reads?

It is true that the later has lower availability since losing a node will return an error, but a successful read will always be consistent.

###  Suggest a fix

READ_CL=ALL should always guarantee consistent reads for any WRITE_CL != ANY

**Comment by bhalevy** [comment]
@tgrabiec am I hallucinating? :)

**Comment by tgrabiec** [comment]
I think you're right, {READ_CL=ALL, WRITE_CL=QUORUM} should be consistent, since the read set always overlaps with any past write set.

**Comment by tzach** [comment]
AFAICS, this issue was already fixed by https://github.com/scylladb/scylladb/commit/04b483e2867ef702765ba5e5c8c8a9ac76d60745
fixed in https://opensource.docs.scylladb.com/master/cql/consistency-calculator.html
and need to be backported.

@bhalevy is it the case?

**Comment by bhalevy** [comment]
> AFAICS, this issue was already fixed by [04b483e](https://github.com/scylladb/scylladb/commit/04b483e2867ef702765ba5e5c8c8a9ac76d60745) fixed in [opensource.docs.scylladb.com/master/cql/consistency-calculator.html](https://opensource.docs.scylladb.com/master/cql/consistency-calculator.html) and need to be backported.
> 
> @bhalevy is it the case?

no.  It's not fixed.
With current master (52f1168a3d), https://opensource.docs.scylladb.com/master/cql/consistency-calculator.html is still inconsistent.
- Nodes = 3
- Replication factor = 3
- Read consistency level = **QUORUM**, Write consistency level = ALL
  - Your reads are consistent
  - You can lose **1** nodes without failing reads
  - You can lose 2 nodes without data loss
- Read consistency level = **ALL**, Write consistency level = ALL
  - Your reads are consistent
  - You can lose **0** nodes without failing reads
  - You can lose 2 nodes without data loss

Looks like we need an automated GUI test for it.

**Comment by bhalevy** [comment]
Yes, it seems to be fixed.

That said, it seems like a good idea to have an automated regression test for it, to make sure it doesn't break.
Cc @roydahan
