### ISSUE TITLE
Create schema with autoresize rf for multidc cluster with tablets enabled and configured with on dc with single zero token node failed and terminate the c-s

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylladb#20684]
## Packages

Scylla version: `6.2.0~dev-20240916.870d1c16f70c` with build-id `ba54fa6888566c0694ad3f85d3076f346281c16c`

Kernel Version: `6.8.0-1016-aws`

## Issue description

- [x] This issue is NOT a regression.
- [ ] It is unknown if this issue is a regression.

I have configured cluster DC1(eu-westscylla_node_west): 3(token nodes); DC2(eu-west-2scylla_node_west): 4 (3 token and 1 zerotoken nodes); DC3 (eu-northscylla_node_north): 1 zero token node. 

Cluster configured with tablets enabled.
As work load next c-s stress command was started:
`cassandra-stress write cl=LOCAL_QUORUM n=20971520 -schema 'replication(strategy=NetworkTopologyStrategy,replication_factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native -rate threads=80 -pop seq=1..20971520 -col 'n=FIXED(10) size=FIXED(512)' -log interval=5`

But  it terminated with error: Nodetool status shows only token nodes. ( known issue)
```
< t:2024-09-17 16:10:26,966 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.3.157>: Datacenter: eu-west-2scylla_node_west
< t:2024-09-17 16:10:26,966 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.3.157>: =====================================
< t:2024-09-17 16:10:26,966 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.3.157>: Status=Up/Down
< t:2024-09-17 16:10:26,966 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.3.157>: |/ State=Normal/Leaving/Joining/Moving
< t:2024-09-17 16:10:26,966 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.3.157>: -- Address    Load    Tokens Owns Host ID                              Rack
< t:2024-09-17 16:10:26,966 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.3.157>: UN 10.3.0.71  1.67 MB 256    ?    0e1985f8-3e26-430c-a9bb-805f511e844d 2a  
< t:2024-09-17 16:10:26,966 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.3.157>: UN 10.3.1.121 1.69 MB 256    ?    727cd8d2-f3d4-46b7-9d59-f8fcf2800928 2a  
< t:2024-09-17 16:10:26,966 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.3.157>: UN 10.3.2.112 1.62 MB 256    ?    6bb5d7f3-3ad1-4c8a-8067-29dffe026e9e 2a  
< t:2024-09-17 16:10:26,966 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.3.157>: Datacenter: eu-westscylla_node_west
< t:2024-09-17 16:10:26,966 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.3.157>: ===================================
< t:2024-09-17 16:10:26,966 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.3.157>: Status=Up/Down
< t:2024-09-17 16:10:26,966 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.3.157>: |/ State=Normal/Leaving/Joining/Moving
< t:2024-09-17 16:10:26,966 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.3.157>: -- Address    Load    Tokens Owns Host ID                              Rack
< t:2024-09-17 16:10:26,966 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.3.157>: UN 10.4.0.208 1.60 MB 256    ?    6d67e87a-6491-4334-b0db-599874cdc14c 1a  
< t:2024-09-17 16:10:26,966 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.3.157>: UN 10.4.3.157 1.60 MB 256    ?    1a339dc4-8e10-4444-a83b-f7374954e452 1a  
< t:2024-09-17 16:10:26,966 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.3.157>: UN 10.4.3.98  1.51 MB 256    ?    a77bca02-2792-430d-a201-bba7c7916dd0 1a  
< t:2024-09-17 16:10:26,966 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.3.157>: 
< t:2024-09-17 16:10:26,966 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.3.157>: Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
< t:2024-09-17 16:10:26,974 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.249>: WARN  [main] 2024-09-17 16:10:26,974 ControlConnection.java:1004 - Found invalid row in system.peers: [peer=/10.0.2.104, missing native_transport_address, missing native_transport_port, missing native_transport_port_ssl, tokens=null]. This is likely a gossip or snitch issue, this host will be ignored.
< t:2024-09-17 16:10:26,978 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.249>: WARN  [main] 2024-09-17 16:10:26,977 ControlConnection.java:1004 - Found invalid row in system.peers: [peer=/10.3.1.205, missing native_transport_address, missing native_transport_port, missing native_transport_port_ssl, tokens=null]. This is likely a gossip or snitch issue, this host will be ignored.
< t:2024-09-17 16:10:27,006 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.3.1.185>: WARN  [cluster1-nio-worker-7] 2024-09-17 16:10:26,999 RequestHandler.java:303 - Query '[0 bound values] CREATE KEYSPACE IF NOT EXISTS "keyspace1" WITH replication = {'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy', 'replication_factor' : '3'} AND durable_writes = true;' generated server side warning(s): Tables in this keyspace will be replicated using Tablets and will not support CDC, LWT and counters features. To use CDC, LWT or counters, drop this keyspace and re-create it without tablets by adding AND TABLETS = {'enabled': false} to the CREATE KEYSPACE statement.
< t:2024-09-17 16:10:27,094 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.249>: WARN  [main] 2024-09-17 16:10:27,093 ReplicationStategy.java:204 - Error while computing token map for keyspace keyspace1 with datacenter eu-northscylla_node_north: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings.
< t:2024-09-17 16:10:27,162 f:db_log_reader.py l:125  c:sdcm.db_log_reader   p:DEBUG > 2024-09-17T16:10:27.099+00:00 multi-dc-rackaware-feature--db-node-99408bc4-2     !INFO | systemd-logind[575]: New session 21 of user scyllaadm.
< t:2024-09-17 16:10:27,162 f:db_log_reader.py l:125  c:sdcm.db_log_reader   p:DEBUG > 2024-09-17T16:10:27.099+00:00 multi-dc-rackaware-feature--db-node-99408bc4-2     !INFO | systemd[1]: Started session-21.scope - Session 21 of User scyllaadm.
< t:2024-09-17 16:10:27,162 f:db_log_reader.py l:125  c:sdcm.db_log_reader   p:DEBUG > 2024-09-17T16:10:27.099+00:00 multi-dc-rackaware-feature--db-node-99408bc4-2     !INFO | scylla[6486]:  [shard 0: gms] schema_tables - Creating keyspace keyspace1
< t:2024-09-17 16:10:27,162 f:db_log_reader.py l:125  c:sdcm.db_log_reader   p:DEBUG > 2024-09-17T16:10:27.099+00:00 multi-dc-rackaware-feature--db-node-99408bc4-2     !INFO | scylla[6486]:  [shard 0: gms] migration_manager - Gossiping my schema version 5a2b954c-750f-11ef-8ad4-848a90059e08
< t:2024-09-17 16:10:27,162 f:db_log_reader.py l:125  c:sdcm.db_log_reader   p:DEBUG > 2024-09-17T16:10:27.099+00:00 multi-dc-rackaware-feature--db-node-99408bc4-2     !INFO | scylla[6486]:  [shard 0: gms] schema_tables - Schema version changed to 5a2b954c-750f-11ef-8ad4-848a90059e08
< t:2024-09-17 16:10:27,202 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.249>: INFO  [main] 2024-09-17 16:10:27,201 RackAwareRoundRobinPolicy.java:112 - Using provided data-center name 'eu-westscylla_node_west' for RackAwareRoundRobinPolicy
< t:2024-09-17 16:10:27,202 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.249>: INFO  [main] 2024-09-17 16:10:27,201 RackAwareRoundRobinPolicy.java:114 - Using provided rack name '1a' for RackAwareRoundRobinPolicy
< t:2024-09-17 16:10:27,204 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.249>: INFO  [main] 2024-09-17 16:10:27,203 Cluster.java:1810 - New Cassandra host /10.3.1.121:9042 added
< t:2024-09-17 16:10:27,204 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.249>: INFO  [main] 2024-09-17 16:10:27,203 Cluster.java:1810 - New Cassandra host /10.4.3.98:9042 added
< t:2024-09-17 16:10:27,204 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.249>: INFO  [main] 2024-09-17 16:10:27,203 Cluster.java:1810 - New Cassandra host /10.4.3.157:9042 added
< t:2024-09-17 16:10:27,204 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.249>: INFO  [main] 2024-09-17 16:10:27,203 Cluster.java:1810 - New Cassandra host /10.3.2.112:9042 added
< t:2024-09-17 16:10:27,204 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.249>: INFO  [main] 2024-09-17 16:10:27,204 Cluster.java:1810 - New Cassandra host /10.4.0.208:9042 added
< t:2024-09-17 16:10:27,204 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.249>: INFO  [main] 2024-09-17 16:10:27,204 Cluster.java:1810 - New Cassandra host /10.3.0.71:9042 added
< t:2024-09-17 16:10:27,205 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.249>: Connected to cluster: multi-dc-rackaware-feature--db-cluster-99408bc4, max pending requests per connection null, max connections per host 8
< t:2024-09-17 16:10:27,206 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.249>: Datatacenter: eu-westscylla_node_west; Host: /10.4.3.98; Rack: 1a
< t:2024-09-17 16:10:27,206 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.249>: Datatacenter: eu-west-2scylla_node_west; Host: /10.3.2.112; Rack: 2a
< t:2024-09-17 16:10:27,206 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.249>: Datatacenter: eu-westscylla_node_west; Host: /10.4.0.208; Rack: 1a
< t:2024-09-17 16:10:27,207 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.249>: Datatacenter: eu-west-2scylla_node_west; Host: /10.3.1.121; Rack: 2a
< t:2024-09-17 16:10:27,207 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.249>: Datatacenter: eu-west-2scylla_node_west; Host: /10.3.0.71; Rack: 2a
< t:2024-09-17 16:10:27,208 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.249>: Datatacenter: eu-westscylla_node_west; Host: /10.4.3.157; Rack: 1a
< t:2024-09-17 16:10:27,214 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.249>: WARN  [cluster1-worker-0] 2024-09-17 16:10:27,213 ReplicationStategy.java:204 - Error while computing token map for keyspace keyspace1 with datacenter eu-northscylla_node_north: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings.
< t:2024-09-17 16:10:27,226 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.249>: INFO  [main] 2024-09-17 16:10:27,223 HostConnectionPool.java:200 - Using advanced port-based shard awareness with /10.4.3.98:9042
< t:2024-09-17 16:10:27,275 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.249>: INFO  [main] 2024-09-17 16:10:27,274 HostConnectionPool.java:200 - Using advanced port-based shard awareness with /10.4.3.157:9042
< t:2024-09-17 16:10:27,294 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.249>: INFO  [main] 2024-09-17 16:10:27,293 HostConnectionPool.java:200 - Using advanced port-based shard awareness with /10.4.0.208:9042

< t:2024-09-17 16:10:27,214 f:base.py         l:231  c:RemoteLibSSH2CmdRunner p:DEBUG > <10.4.0.249>: WARN  [cluster1-worker-0] 2024-09-17 16:10:27,213 ReplicationStategy.java:204 - Error while computing token map for keyspace keyspace1 with datacenter eu-northscylla_node_north: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings.
Query is next: `CREATE KEYSPACE IF NOT EXISTS "keyspace1" WITH replication = {'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy', 'replication_factor' : '3'} AND durable_writes = true;' ` generated server side warning(s): Tables in this keyspace will be replicated using Tablets and will not support CDC, LWT and counters features. To use CDC, LWT or counters, drop this keyspace and re-create it without tablets by adding AND TABLETS = {'enabled': false} to the CREATE KEYSPACE statement.
```

C-s log contains next errors:
```
Connected to cluster: multi-dc-rackaware-feature--db-cluster-99408bc4, max pending requests per connection null, max connections per host 8
Datatacenter: eu-westscylla_node_west; Host: /10.4.3.98; Rack: 1a
Datatacenter: eu-west-2scylla_node_west; Host: /10.3.2.112; Rack: 2a
Datatacenter: eu-westscylla_node_west; Host: /10.4.0.208; Rack: 1a
Datatacenter: eu-west-2scylla_node_west; Host: /10.3.1.121; Rack: 2a
Datatacenter: eu-west-2scylla_node_west; Host: /10.3.0.71; Rack: 2a
Datatacenter: eu-westscylla_node_west; Host: /10.4.3.157; Rack: 1a
WARN  [cluster1-worker-0] 2024-09-17 16:10:27,213 ReplicationStategy.java:204 - Error while computing token map for keyspace keyspace1 with datacenter eu-northscylla_node_north: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings.
INFO  [main] 2024-09-17 16:10:27,223 HostConnectionPool.java:200 - Using advanced port-based shard awareness with /10.4.3.98:9042
INFO  [main] 2024-09-17 16:10:27,274 HostConnectionPool.java:200 - Using advanced port-based shard awareness with /10.4.3.157:9042
INFO  [main] 2024-09-17 16:10:27,293 HostConnectionPool.java:200 - Using advanced port-based shard awareness with /10.4.0.208:9042
WARN  [cluster1-worker-2] 2024-09-17 16:10:28,143 ReplicationStategy.java:204 - Error while computing token map for keyspace keyspace1 with datacenter eu-northscylla_node_north: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings.
java.lang.RuntimeException: Encountered exception creating schema
        at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:105)
        at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpaces(SettingsSchema.java:74)
        at org.apache.cassandra.stress.settings.StressSettings.maybeCreateKeyspaces(StressSettings.java:230)
        at org.apache.cassandra.stress.StressAction.run(StressAction.java:58)
        at org.apache.cassandra.stress.Stress.run(Stress.java:143)
        at org.apache.cassandra.stress.Stress.main(Stress.java:62)
Caused by: com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException: Datacenter eu-northscylla_node_north doesn't have enough token-owning nodes for replication_factor=3
        at com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException.copy(InvalidConfigurationInQueryException.java:38)
        at com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException.copy(InvalidConfigurationInQueryException.java:27)
        at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
        at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:310)
        at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:58)
        at org.apache.cassandra.stress.util.JavaDriverClient.execute(JavaDriverClient.java:215)
        at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:94)
        ... 5 more
```

It seems, that auto-resize replication factor in multidc with zero token nodes is not working with tablets.

while run with https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/longevity-multi-dc-rack-aware-zero-token-dc/11/ with exactly same config and disabled tablets, c-s reported same warning but continue its work and start send traffic:
```
Datatacenter: eu-west-2scylla_node_west; Host: /10.3.1.171; Rack: 2a
Datatacenter: eu-westscylla_node_west; Host: /10.4.3.121; Rack: 1a
INFO  [main] 2024-09-18 12:55:58,068 HostConnectionPool.java:200 - Using advanced port-based shard awareness with /10.4.1.4:9042
INFO  [main] 2024-09-18 12:55:58,099 HostConnectionPool.java:200 - Using advanced port-based shard awareness with /10.4.3.214:9042
INFO  [main] 2024-09-18 12:55:58,115 HostConnectionPool.java:200 - Using advanced port-based shard awareness with /10.4.3.121:9042
WARN  [cluster1-worker-1] 2024-09-18 12:55:59,182 ReplicationStategy.java:204 - Error while computing token map for keyspace keyspace1 with datacenter eu-northscylla_node_north: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings.
WARN  [cluster1-worker-3] 2024-09-18 12:56:02,625 ReplicationStategy.java:204 - Error while computing token map for keyspace keyspace1 with datacenter eu-northscylla_node_north: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings.
Created keyspaces. Sleeping 3s for propagation.
Sleeping 2s...
Running WRITE with 80 threads for 20971520 iteration
type       total ops,    op/s,    pk/s,   row/s,    mean,     med,     .95,     .99,    .999,     max,   time,   stderr, errors,  gc: #,  max ms,  sum ms,  sdv ms,      mb
Failed to connect over JMX; not collecting these stats
total,         88601,   17720,   17720,   17720,     3.5,     2.5,     9.5,    19.1,    45.1,    79.2,    5.0,  0.00000,      0,      0,       0,       0,       0,       0
total,        256394,   33559,   33559,   33559,     
```

Keyspace created with next rf and DCes):
```
cqlsh> desc keyspace1;

CREATE KEYSPACE keyspace1 WITH replication = {'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy', 'eu-northscylla_node_north': '3', 'eu-west-2scylla_node_west': '3', 'eu-westscylla_node_west': '3'} AND durable_writes = true;

CREATE TABLE keyspace1.standard1 (
    key blob,
    "C0" blob,
    "C1" blob,
    "C2" blob,
    "C3" blob,
    "C4" blob,
    "C5" blob,
    "C6" blob,
    "C7" blob,
    "C8" blob,
    "C9" blob,
    PRIMARY KEY (key)
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {}
    AND crc_check_chance = 1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND speculative_retry = '99.0PERCENTILE'
    AND tombstone_gc = {'mode': 'timeout', 'propagation_delay_in_seconds': '3600'};
```

## Impact

*Describe the impact this issue causes to the user.*

## How frequently does it reproduce?

*Describe the frequency with how this issue can be reproduced.*

## Installation details

Cluster size: 6 nodes (i4i.2xlarge)

Scylla Nodes used in this run:
- multi-dc-rackaware-feature--db-node-99408bc4-8 (13.48.70.86 | 10.0.2.104) (shards: 4)
- multi-dc-rackaware-feature--db-node-99408bc4-7 (3.8.172.174 | 10.3.1.205) (shards: 4)
- multi-dc-rackaware-feature--db-node-99408bc4-6 (18.170.220.40 | 10.3.2.112) (shards: 7)
- multi-dc-rackaware-feature--db-node-99408bc4-5 (18.175.115.165 | 10.3.0.71) (shards: 7)
- multi-dc-rackaware-feature--db-node-99408bc4-4 (35.176.190.55 | 10.3.1.121) (shards: 7)
- multi-dc-rackaware-feature--db-node-99408bc4-3 (34.253.93.186 | 10.4.0.208) (shards: 7)
- multi-dc-rackaware-feature--db-node-99408bc4-2 (3.252.145.18 | 10.4.3.157) (shards: 7)
- multi-dc-rackaware-feature--db-node-99408bc4-1 (3.253.99.51 | 10.4.3.98) (shards: 7)

OS / Image: `ami-02a7f524e91e35664 ami-0094c7e2362289d20 ami-0e00401f614e6eb3a` (aws: undefined_region)

Test: `longevity-multi-dc-rack-aware-zero-token-dc`
Test id: `99408bc4-ff3a-48e0-9b37-65c3cf001435`
Test name: `scylla-staging/abykov/longevity-multi-dc-rack-aware-zero-token-dc`
Test method: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):

- [longevity-multi-dc-rack-aware.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/0bcf79025d957a9640ee0ac8ce7fb675874afd88/test-cases/longevity/longevity-multi-dc-rack-aware.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 99408bc4-ff3a-48e0-9b37-65c3cf001435`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=99408bc4-ff3a-48e0-9b37-65c3cf001435)
- Show all stored logs command: `$ hydra investigate show-logs 99408bc4-ff3a-48e0-9b37-65c3cf001435`

## Logs:
- **db-cluster-99408bc4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/99408bc4-ff3a-48e0-9b37-65c3cf001435/20240917_161358/db-cluster-99408bc4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/99408bc4-ff3a-48e0-9b37-65c3cf001435/20240917_161358/db-cluster-99408bc4.tar.gz)
- **sct-runner-events-99408bc4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/99408bc4-ff3a-48e0-9b37-65c3cf001435/20240917_161358/sct-runner-events-99408bc4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/99408bc4-ff3a-48e0-9b37-65c3cf001435/20240917_161358/sct-runner-events-99408bc4.tar.gz)
- **sct-99408bc4.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/99408bc4-ff3a-48e0-9b37-65c3cf001435/20240917_161358/sct-99408bc4.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/99408bc4-ff3a-48e0-9b37-65c3cf001435/20240917_161358/sct-99408bc4.log.tar.gz)
- **loader-set-99408bc4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/99408bc4-ff3a-48e0-9b37-65c3cf001435/20240917_161358/loader-set-99408bc4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/99408bc4-ff3a-48e0-9b37-65c3cf001435/20240917_161358/loader-set-99408bc4.tar.gz)
- **monitor-set-99408bc4.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/99408bc4-ff3a-48e0-9b37-65c3cf001435/20240917_161358/monitor-set-99408bc4.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/99408bc4-ff3a-48e0-9b37-65c3cf001435/20240917_161358/monitor-set-99408bc4.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/longevity-multi-dc-rack-aware-zero-token-dc/10/)
[Argus](https://argus.scylladb.com/test/bbd702fb-2f87-4b0b-a068-c2c83d74cb77/runs?additionalRuns[]=99408bc4-ff3a-48e0-9b37-65c3cf001435)
</details>

**Comment by bhalevy** [comment]
> > CREATE KEYSPACE IF NOT EXISTS "keyspace1" WITH replication = {'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy', 'replication_factor' : '3'}
> 
> Isn't replication factor auto-expansion supposed to be rejected in tablets mode? cc @ptrsmrn @bhalevy

Only in ALTER KEYSPACE. It's fine in CREATE

**Comment by kbr-scylla** [comment]
We should reject the attempts to assign more RF than there are nodes in a given DC, as described in https://github.com/scylladb/scylladb/issues/20356. (Whether through auto-expansion or not.)

Then the initial CREATE here would fail. And the test would have to be adjusted. Which BTW you can do right away @aleksbykov so it doesn't block further testing of zero-token nodes

Still it's interesting why:
- in vnodes mode cassandra-stress only prints a warning but progresses and successfully generates load to the cluster
- but in tablets mode this causes a failure

I **suspect** that this is somehow related to the tablets-specific routing logic in the driver. The vnodes logic somehow handles the situation (perhaps ignoring the DC and routing to other DCs?) while the tablets logic doesn't.

cc @fruch @dkropachev @sylwiaszunejko 

But I'm not sure.

I also suspect that the error doesn't require zero-token nodes
```
Error while computing token map for keyspace keyspace1 with datacenter eu-northscylla_node_north: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings
```

it just requires the **RF to be greater than the number of nodes in this DC**.

Anyway I think the investigation should be started from the drivers angle, and if it turns out that there's a difference between vnodes and tablets logic, a decision should be made if we're to handle it differently in drivers, or perhaps rely on https://github.com/scylladb/scylladb/issues/20356 for a complete fix.

Assigning to the drivers team for now.

**Comment by swasik** [comment]
> Assigning to the drivers team for now.

@dkropachev could you confirm that you agree with Karol's assignment to your team? I prefer to validate as this is P1 related to elastic cloud without much updates recently.

**Comment by fruch** [comment]
> > Assigning to the drivers team for now.
> 
> [@dkropachev](https://github.com/dkropachev) could you confirm that you agree with Karol's assignment to your team? I prefer to validate as this is P1 related to elastic cloud without much updates recently.

`s/Karol/Kamil/`

**Comment by dkropachev** [comment]
> > Assigning to the drivers team for now.
> 
> [@dkropachev](https://github.com/dkropachev) could you confirm that you agree with Karol's assignment to your team? I prefer to validate as this is P1 related to elastic cloud without much updates recently.

Agree, it is P1

**Comment by dkropachev** [comment]
@aleksbykov , @fruch , we are tring to indetify scope of it, could you please point me to what makes `replication factor` to be `auto-resize` in this test ?

**Comment by bhalevy** [comment]
@aleksbykov @fruch ping ☝

**Comment by bhalevy** [comment]
> [@aleksbykov](https://github.com/aleksbykov) , [@fruch](https://github.com/fruch) , we are tring to indetify scope of it, could you please point me to what makes `replication factor` to be `auto-resize` in this test ?

@dkropachev `replication(strategy=NetworkTopologyStrategy,replication_factor=3)` set replication factor to 3 using a the "wildcard" `replication_factor` option, rather than per-dc rf, therefore it induces the auto-expansion algorithm.

That said, we need to test keyspace creation with tablets and zero-token nodes also with explicit per-dc replication factor configuration.  I'm not sure about the level of integration of tablets replica allocation with zero-token nodes.

**Comment by bhalevy** [comment]
@regevran, @xemul please be available for any questions on this matter

**Comment by mykaul** [comment]
I'm not sure it's a P1 (re-reading this issue). @bhalevy - either re-prioritize or let's make sure we make progress here.

**Comment by bhalevy** [comment]
> I'm not sure it's a P1 (re-reading this issue). [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/20910904?s=64&amp;u=ac01f571ac61e5408a25429beb691bbeaa05102c&amp;v=4">@bhalevy](https://github.com/bhalevy) - either re-prioritize or let's make sure we make progress here.

I think it is P1.
But @kbr-scylla why do you think the issue could be on the driver side?

Shouldn't the following loop skip datacenters that have only zero-token nodes?
https://github.com/scylladb/scylladb/blob/f744007e13657491082ccf7023d07947f2b23ea1/cql3/statements/ks_prop_defs.cc#L68-L70

Cc @ptrsmrn

**Comment by dkropachev** [comment]
@Bouncheck , can you please take a look at it from the perspective of https://github.com/scylladb/java-driver/issues/317.

**Comment by kbr-scylla** [comment]
@bhalevy 


To be precise I think there are two issues.

- CREATE with rf=3 succeeded, and allocated 3 replicas to DC3. But DC3 does not have enough nodes. It has only one node, which is also a zero-token node, so it can allocate 0 replicas at most. Therefore CREATE should fail and advise the user to explicitly set the number of replicas in DC3 to a lower number (0 in this case) in the CREATE statement. This is a Scylla-side issue: https://github.com/scylladb/scylladb/issues/20356.
- Java driver fails with: `Error while computing token map for keyspace keyspace1 with datacenter eu-northscylla_node_north: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings.` Is this a driver issue? You could argue that, if we fix the CREATE problem, the situation would never happen, therefore we would not encounter this error. So we can decide that there is no question and we can move on. OTOH, in vnodes mode, Java driver works in this scenario; it sends queries to the other DCs. So you could argue that it's a regression in the driver with tablets compared to vnodes, so must be fixed.

So:
- there is definitely an issue on Scylla side. It's https://github.com/scylladb/scylladb/issues/20356. But honestly, it's not a P1 -- if you're a ScyllaDB user, just don't create a keyspace with wrong RF.
- there is or there isn't an issue in driver; one can argue both ways. If there is an issue, I also think it's not a P1, since the above is not a P1.

**Comment by kbr-scylla** [comment]
> Shouldn't the following loop skip datacenters that have only zero-token nodes?

I would prefer throwing an error, forcing the user to explicitly set a lower RF, so they don't get surprised by ScyllaDB "fixing" the problem for them in unpredictable ways.

**Comment by bhalevy** [comment]
> > Shouldn't the following loop skip datacenters that have only zero-token nodes?
> 
> I would prefer throwing an error, forcing the user to explicitly set a lower RF, so they don't get surprised by ScyllaDB "fixing" the problem for them in unpredictable ways.

It's predictable if it's well documented.

**Comment by bhalevy** [comment]
I see zero-token nodes added by the storage admin, while keyspace creation could be done by the app, who might not be aware of the tie-breaker datacenter, so expanding replication_factor by ignoring this DC will reduce the friction and prevent errors.
I'm not a big fan of the auto-expand feature, but as long as we support it, it should be simple to use, IMO.

**Comment by kbr-scylla** [comment]
It will prevent a shallow error that pops up in your face immediately and takes 5 seconds to fix; in exchange you get an error that causes frustration further down the line because you don't have the number of replicas you think you did and suddenly you're dealing with unavailability on a live keyspace used by an application, etc.

**Comment by dkropachev** [comment]
> [@bhalevy](https://github.com/bhalevy)
> 
> To be precise I think there are two issues.
> 
> * CREATE with rf=3 succeeded, and allocated 3 replicas to DC3. But DC3 does not have enough nodes. It has only one node, which is also a zero-token node, so it can allocate 0 replicas at most. Therefore CREATE should fail and advise the user to explicitly set the number of replicas in DC3 to a lower number (0 in this case) in the CREATE statement. This is a Scylla-side issue: [prevent creating a keyspace with RF > 0 in an arbiter DC #20356](https://github.com/scylladb/scylladb/issues/20356).

UX-wise it would be better just to ignore datacenters with zero-token nodes only.

> * Java driver fails with: `Error while computing token map for keyspace keyspace1 with datacenter eu-northscylla_node_north: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings.` Is this a driver issue? You could argue that, if we fix the CREATE problem, the situation would never happen, therefore we would not encounter this error. So we can decide that there is no question and we can move on. OTOH, in vnodes mode, Java driver works in this scenario; it sends queries to the other DCs. So you could argue that it's a regression in the driver with tablets compared to vnodes, so must be fixed.

@Bouncheck , working on adding this test to integration suite of the driver.

**Comment by dani-tweig** [comment]
This issue, marked for 2025.1.0, has not been touched for over a month.
Is there any update?
is 2025.1.0 still reasonable?

**Comment by mykaul** [comment]
@bhalevy ^^^?

**Comment by bhalevy** [comment]
> [@bhalevy](https://github.com/bhalevy) ^^^?

@mykaul I'm barely involved in this issue.
@kbr-scylla is your go-to person here, I believe

**Comment by dkropachev** [comment]
Please retest with new c-s, it should be fixed there.

**Comment by roydahan** [comment]
@aleksbykov we should have now newer c-s with newest java driver that should handle zero tokens better.
Can you please retest and see if it works well now?

**Comment by aleksbykov** [comment]
@dkropachev , i still get issue reproduce. Is version of cassandra-stress valid?
```
INFO  [main] 2025-03-05 13:16:43,292 GuavaCompatibility.java:204 - Detected Guava >= 19 in the classpath, using modern compatibility layer
INFO  [main] 2025-03-05 13:16:43,302 Cluster.java:280 - DataStax Java driver 3.11.5.3 for Apache Cassandra

Datatacenter: eu-westscylla_node_west; Host: /10.4.10.89; Rack: 1c
INFO  [main] 2025-03-05 13:16:43,841 HostConnectionPool.java:200 - Using advanced port-based shard awareness with /10.4.9.128:9042
INFO  [main] 2025-03-05 13:16:43,886 HostConnectionPool.java:200 - Using advanced port-based shard awareness with /10.4.10.89:9042
INFO  [main] 2025-03-05 13:16:43,904 HostConnectionPool.java:200 - Using advanced port-based shard awareness with /10.4.11.187:9042
INFO  [main] 2025-03-05 13:16:43,919 HostConnectionPool.java:200 - Using advanced port-based shard awareness with /10.4.10.126:9042
WARN  [cluster1-nio-worker-6] 2025-03-05 13:16:43,976 RequestHandler.java:303 - Query '[0 bound values] CREATE KEYSPACE IF NOT EXISTS "keyspace1" WITH replication = {'class': 'org.apache.cassandra.locator.NetworkTopologyStrategy', 'replication_factor' : '3'} AND durable_writes = true;' generated server side warning(s): Tables in this keyspace will be replicated using Tablets and will not support CDC, LWT and counters features. To use CDC, LWT or counters, drop this keyspace and re-create it without tablets by adding AND TABLETS = {'enabled': false} to the CREATE KEYSPACE statement.
WARN  [cluster1-worker-1] 2025-03-05 13:16:45,025 ReplicationStategy.java:204 - Error while computing token map for keyspace keyspace1 with datacenter eu-northscylla_node_north: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings.
WARN  [cluster1-worker-2] 2025-03-05 13:16:46,205 ReplicationStategy.java:204 - Error while computing token map for keyspace keyspace1 with datacenter eu-northscylla_node_north: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings.
java.lang.RuntimeException: Encountered exception creating schema
        at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:105)
        at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpaces(SettingsSchema.java:74)
        at org.apache.cassandra.stress.settings.StressSettings.maybeCreateKeyspaces(StressSettings.java:230)
        at org.apache.cassandra.stress.StressAction.run(StressAction.java:58)
        at org.apache.cassandra.stress.Stress.run(Stress.java:151)
        at org.apache.cassandra.stress.Stress.main(Stress.java:70)
Caused by: com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException: Datacenter eu-northscylla_node_north doesn't have enough token-owning nodes for replication_factor=3
        at com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException.copy(InvalidConfigurationInQueryException.java:38)
        at com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException.copy(InvalidConfigurationInQueryException.java:27)
        at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
        at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:310)
        at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:58)
        at org.apache.cassandra.stress.util.JavaDriverClient.execute(JavaDriverClient.java:263)
        at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:94)
        ... 5 more
```

next cassandra-stress was used:
```
< t:2025-03-05 13:16:42,007 f:tooling_reporter.py l:79   c:sdcm.reporting.tooling_reporter p:INFO  > CassandraStressVersionReporter(): Collected cassandra-stress output:
< t:2025-03-05 13:16:42,007 f:tooling_reporter.py l:79   c:sdcm.reporting.tooling_reporter p:INFO  > Version: 3.17.0
< t:2025-03-05 13:16:42,007 f:tooling_reporter.py l:79   c:sdcm.reporting.tooling_reporter p:INFO  > scylla-java-driver: 3.11.5.3
< t:2025-03-05 13:16:42,008 f:tooling_reporter.py l:93   c:sdcm.reporting.tooling_reporter p:INFO  > Result:
< t:2025-03-05 13:16:42,008 f:tooling_reporter.py l:93   c:sdcm.reporting.tooling_reporter p:INFO  > {'cassandra-stress': '3.17.0', 'scylla-java-driver': '3.11.5.3'}
< t:2025-03-05 13:16:42,008 f:tooling_reporter.py l:35   c:sdcm.reporting.tooling_reporter p:INFO  > CassandraStressJavaDriverVersionReporter(): java-driver version is 3.11.5.3

```

**Comment by Bouncheck** [comment]
> [@aleksbykov](https://github.com/aleksbykov) we should have now newer c-s with newest java driver that should handle zero tokens better. Can you please retest and see if it works well now?

@roydahan handling is better now but I believe I haven't made any changes to handle this scenario. My understanding was that this is a server issue.

**Comment by roydahan** [comment]
This looks like something else.
IIUC this is a schema creation error for an unsupported configuration.
@aleksbykov is it the original test in the description above?
Please verify the configuration because now there are some limitations when using tablets.

**Comment by aleksbykov** [comment]
@roydahan , it is the same original test as in description, and c-s failed with exact the same error message and only if tables is enabled by default for all keyspaces.
without tablets disabled by default: https://argus.scylladb.com/tests/scylla-cluster-tests/6a31c4e4-9c0d-4b72-9603-7a78648d3652  job passed
with tablets enabled  by default: https://argus.scylladb.com/tests/scylla-cluster-tests/39c9f6bf-0450-43fd-89c3-44f8aac8ca41 job failed.

**Comment by Bouncheck** [comment]
Just to clarify, this looks the same, but I don't see why the driver would be faulty.
This is just a warning:
```
WARN  [cluster1-worker-1] 2025-03-05 13:16:45,025 ReplicationStategy.java:204 - Error while computing token map for keyspace keyspace1 with datacenter eu-northscylla_node_north: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings.
WARN  [cluster1-worker-2] 2025-03-05 13:16:46,205 ReplicationStategy.java:204 - Error while computing token map for keyspace keyspace1 with datacenter eu-northscylla_node_north: could not achieve replication factor 3 (found 0 replicas only), check your keyspace replication settings.
```

This is the actual failure pointing to c-s:
```
java.lang.RuntimeException: Encountered exception creating schema
        at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:105)
        at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpaces(SettingsSchema.java:74)
        at org.apache.cassandra.stress.settings.StressSettings.maybeCreateKeyspaces(StressSettings.java:230)
        at org.apache.cassandra.stress.StressAction.run(StressAction.java:58)
        at org.apache.cassandra.stress.Stress.run(Stress.java:151)
        at org.apache.cassandra.stress.Stress.main(Stress.java:70)
Caused by: com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException: Datacenter eu-northscylla_node_north doesn't have enough token-owning nodes for replication_factor=3
        at com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException.copy(InvalidConfigurationInQueryException.java:38)
        at com.datastax.driver.core.exceptions.InvalidConfigurationInQueryException.copy(InvalidConfigurationInQueryException.java:27)
        at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
        at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:310)
        at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:58)
        at org.apache.cassandra.stress.util.JavaDriverClient.execute(JavaDriverClient.java:263)
        at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:94)
        ... 5 more
```
It's (0x2300) error from the server. IIUC if you ran the queries (create ks then table) with cqlsh instead of the driver you would get the same result.

**Comment by roydahan** [comment]
@kostja can someone from your group take a look at it?

**Comment by patjed41** [comment]
#23138 that has just been queued will fix the server-side issue (for now only with `rf_rack_valid_keyspaces: true`). The CREATE KS statement with RF>0 in a DC with only zero-token nodes will fail on the new guardrail.

It looks like the c-s failure comes from the failure of the CREATE TABLE statement on the server. Note
```
Datacenter eu-northscylla_node_north doesn't have enough token-owning nodes for replication_factor=3
```
This is the current error Scylla throws when you try to create a table in a keyspace with tablets enabled where RF exceeds the number of token-owning nodes in some DC. Yes, currently creating a keyspace with too big RF succeeds, but creating a table fails. Without tablets, both succeed. That's why we hit this error only with tablets. With #23138 in and `rf_rack_valid_keyspaces: true`, we will hit a new error while creating a keyspace, again, only with tablets.

So, the server-side issue is somewhat fixed for now and will be completely fixed when we will change the default value of `rf_rack_valid_keyspaces` to `true`. There is also no driver-side issue. I think we can close this issue, since there is nothing new to do. We only have to adjust the test to set RF=0 in the DC with one zero-token node. @aleksbykov

**Comment by patjed41** [comment]
Closing, nothing new to do

**Comment by patjed41** [comment]
Closing, nothing new to do
