### ISSUE TITLE
test_topology_ops_encrypted.test_topology_ops_encrypted failed with AssertionError

### ISSUE THREAD

**Issue by lsfreitas** [scylladb/scylladb#25809]
Seen: https://jenkins.scylladb.com/job/scylla-2025.3/job/next/115/testReport/cluster/test_topology_ops_encrypted/aarch64___debug___test_py_debug_aarch64___test_topology_ops_encrypted_True__debug_1/

Logs:

[pytest.log](https://github.com/user-attachments/files/22116001/pytest.log)
[scylla-1235.log](https://github.com/user-attachments/files/22115997/scylla-1235.log)
[scylla-1237.log](https://github.com/user-attachments/files/22115999/scylla-1237.log)
[scylla-1238.log](https://github.com/user-attachments/files/22116000/scylla-1238.log)
[scylla-1239.log](https://github.com/user-attachments/files/22115994/scylla-1239.log)
[scylla-1240.log](https://github.com/user-attachments/files/22115998/scylla-1240.log)
[stacktrace.txt](https://github.com/user-attachments/files/22115996/stacktrace.txt)
[test_py.log](https://github.com/user-attachments/files/22115995/test_py.log)

```
request = <FixtureRequest for <Coroutine test_topology_ops_encrypted[True].debug.1>>
manager = <test.pylib.manager_client.ManagerClient object at 0xffff1ce570e0>
tablets_enabled = True
tmp_path = PosixPath('/scylladir/testlog/aarch64/debug/pytest-of-root/pytest-0/test_topology_ops_encrypted_Tr0')

    @pytest.mark.asyncio
    @pytest.mark.parametrize("tablets_enabled", [True, False])
    async def test_topology_ops_encrypted(request, manager: ManagerClient, tablets_enabled: bool, tmp_path):
        """Test basic topology operations using the topology coordinator. But encrypted."""
        d = tmp_path / "keys"
        d.mkdir()
        k = d / "system_key"
        k.write_text('AES/CBC/PKCS5Padding:128:ApvJEoFpQmogvam18bb54g==')
        rf_rack_cfg = {'rf_rack_valid_keyspaces': False}
        cfg = {'tablets_mode_for_new_keyspaces': 'enabled' if tablets_enabled else 'disabled',
               'user_info_encryption': {'enabled': True, 'key_provider': 'LocalFileSystemKeyProviderFactory'},
               'system_key_directory': d.as_posix()}
        cfg = cfg | rf_rack_cfg
        rf = 3
        num_nodes = rf
        if tablets_enabled:
            num_nodes += 1
    
        logger.info("Bootstrapping first node")
        servers = [await manager.server_add(config=cfg)]
    
        logger.info(f"Restarting node {servers[0]}")
        await manager.server_stop_gracefully(servers[0].server_id)
        await manager.server_start(servers[0].server_id)
    
        logger.info("Bootstrapping other nodes")
        servers += await manager.servers_add(num_nodes, config=cfg)
    
        await wait_for_cql_and_get_hosts(manager.cql, servers, time.time() + 60)
        cql = await reconnect_driver(manager)
        finish_writes = await start_writes(cql, rf, ConsistencyLevel.ONE)
    
        logger.info(f"Decommissioning node {servers[0]}")
        await manager.decommission_node(servers[0].server_id)
>       await check_token_ring_and_group0_consistency(manager)

test/cluster/test_topology_ops_encrypted.py:54: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

manager = <test.pylib.manager_client.ManagerClient object at 0xffff1ce570e0>

    async def check_token_ring_and_group0_consistency(manager: ManagerClient) -> None:
        """Ensure that the normal token owners and group 0 members match
           according to each currently running server.
    
           Note that the normal token owners and group 0 members never match
           in the presence of zero-token nodes.
        """
        servers = await manager.running_servers()
        for srv in servers:
            group0_members = await get_current_group0_config(manager, srv)
            group0_ids = {m[0] for m in group0_members}
            token_ring_ids = await get_token_ring_host_ids(manager, srv)
>           assert token_ring_ids == group0_ids
E           AssertionError

test/cluster/util.py:115: AssertionError
```

**Comment by lsfreitas** [comment]
@mykaul this issue seems familiar to me but I don't seem to find any issue open for it which is strange.

**Comment by mykaul** [comment]
@emdroid - does this belong to your team?

**Comment by mykaul** [comment]
Would have been nice if the assert would have printed more information wrt to what is NOT working, such as the token_ring_ids and the group0_ids !

**Comment by emdroid** [comment]
> [@emdroid](https://github.com/emdroid) - does this belong to your team?

It looks like it does, we can at least triage.


> Would have been nice if the assert would have printed more information wrt to what is NOT working, such as the token_ring_ids and the group0_ids !

It's actually strange, as the failed assert usually prints the values

**Comment by emdroid** [comment]
Looking into the pytest.log:
```
00:00:47.501 INFO>  Group 0 members by Server(1237, 127.225.108.30, 127.225.108.30, DEFAULT_DC, DEFAULT_RACK): {('080951c6-c690-4177-8823-66f38a6fb48f', True), ('0d6f7f55-1723-4f34-b3a4-c4715c6a0c6b', True), ('4525241e-a132-446e-97fa-3f6d806cdd98', True), ('0d5f7474-5ad5-4ec9-b440-f60773158947', False), ('d6119087-a42c-4ae7-9304-0de5362ef5fd', True)}
00:00:47.501 DEBUG>  RESTClient fetching GET http://127.225.108.30:10000/storage_service/tokens_endpoint
00:00:47.534 INFO>  Normal endpoints' IPs by Server(1237, 127.225.108.30, 127.225.108.30, DEFAULT_DC, DEFAULT_RACK): {'127.225.108.31', '127.225.108.17', '127.225.108.26', '127.225.108.30'}
00:00:47.534 DEBUG>  RESTClient fetching GET http://127.225.108.30:10000/storage_service/host_id
00:00:47.537 INFO>  All host IDs by Server(1237, 127.225.108.30, 127.225.108.30, DEFAULT_DC, DEFAULT_RACK): {'d6119087-a42c-4ae7-9304-0de5362ef5fd', '080951c6-c690-4177-8823-66f38a6fb48f', '4525241e-a132-446e-97fa-3f6d806cdd98', '0d6f7f55-1723-4f34-b3a4-c4715c6a0c6b'}
00:00:47.537 INFO>  Normal endpoints' host IDs by Server(1237, 127.225.108.30, 127.225.108.30, DEFAULT_DC, DEFAULT_RACK): {'d6119087-a42c-4ae7-9304-0de5362ef5fd', '080951c6-c690-4177-8823-66f38a6fb48f', '4525241e-a132-446e-97fa-3f6d806cdd98', '0d6f7f55-1723-4f34-b3a4-c4715c6a0c6b'}
```

The first log line is determining the group0 members:
```
('080951c6-c690-4177-8823-66f38a6fb48f', True),
('0d6f7f55-1723-4f34-b3a4-c4715c6a0c6b', True),
('4525241e-a132-446e-97fa-3f6d806cdd98', True),
('0d5f7474-5ad5-4ec9-b440-f60773158947', False),
('d6119087-a42c-4ae7-9304-0de5362ef5fd', True)
```

whereas the `group0_ids` are determined by the "Normal endpoints' host IDs":
```
'd6119087-a42c-4ae7-9304-0de5362ef5fd',
'080951c6-c690-4177-8823-66f38a6fb48f',
'4525241e-a132-446e-97fa-3f6d806cdd98',
'0d6f7f55-1723-4f34-b3a4-c4715c6a0c6b'
```

There is one entry missing: the "('0d5f7474-5ad5-4ec9-b440-f60773158947', False)" entry.

The "False" means that the group0 member is not a voter. That node is the one that apparently is being decommissioned:
```
00:00:35.167 DEBUG>  RESTClient fetching PUT http://api/cluster/decommission-node/1235

# scylla-1235.log
INFO  2025-09-02 00:00:03,666 [shard 0:main] init - Setting local host id to 0d5f7474-5ad5-4ec9-b440-f60773158947
```

So - the `get_current_group0_config()` apparently still returns the decommissioned server as a group0 member (this call is done via a lookup to the `system.scylla_local` for the group ID and then `system.raft_state` for the members). The request is apparently going to all servers that are being considered running, in the above case to the server 1237 (127.225.108.30), which seemingly still has the entry of the decommissioned server.

There is a read barrier executed before that call though, which should make sure that all the state is up to date.

Note that the node 1235 that is being decommissioned is initially the topology leader:
```
INFO  2025-09-02 00:00:45,634 [shard 0: gms] raft_topology - coordinator is decommissioning; giving up leadership
```
and the topology leadership is then transferred to the node 1238:
```
INFO  2025-09-02 00:00:45,666 [shard 0:strm] raft_group0 - gaining leadership
```

But looking at the test, this is the expected behavior (i.e., the first node being the topology coordinator and being decommissioned), so the problem appears to be the presence of the decommissioned node entry on the other nodes, This occurrence seems to be pretty rare, as I didn't succeed to reproduce this locally so far.

**Comment by emdroid** [comment]
There was a similar issue in the past: https://github.com/scylladb/scylladb/issues/13518

But that should've been resolved by executing the read barrier before the check: https://github.com/scylladb/scylladb/pull/13756/files

The read barrier call has been changed later changed to be triggered directly bu an API request, but a mentioned it is still present there.

**Comment by calebxyz** [comment]
@enedil so should this go into planning ?

**Comment by patjed41** [comment]
Reproduces with
```diff
diff --git a/service/topology_coordinator.cc b/service/topology_coordinator.cc
index 9126e027da..6ebf38ecf0 100644
--- a/service/topology_coordinator.cc
+++ b/service/topology_coordinator.cc
@@ -2687,6 +2687,7 @@ class topology_coordinator : public endpoint_lifecycle_subscriber {
                 if (shutdown_failed) {
                     node = retake_node(co_await start_operation(), node_id);
                 }
+                co_await sleep(5s);
 
                 // Remove the node from group0 here - in general, it won't be able to leave on its own
                 // because we'll ban it as soon as we tell it to shut down
```

Even with the read barrier in the test, the test can still fail if the read barrier is executed before the decommissioning node is removed from group 0. Very unlikely scenario, but it finally happened after a few years.

Note that removenode and replace don't have this problem because we remove from group 0 nodes being removed/replaced before we mark the topology request as completed (in the `write_both_read_new` handler). Unfortunately, we cannot do the same for decommission. The decommissioning node must be a member of group 0 when we mark the decommission request as completed, so the node can learn about the request completion and shut down.

We could try to make the decommissioning node wait until it leaves group 0 at the end of the decommission handler (`storage_service::raft_decommission`), but that would be a complication beneficial only for tests. So, I think we should just adjust the test and check if there are other tests with the same problem. One idea is to replace `check_token_ring_and_group0_consistency` with `wait_for_token_ring_and_group0_consistency`.

**Comment by patjed41** [comment]
The following test cases have the same problem: `test_change_replication_factor_1_to_0_and_decommission`, `test_data_resurrection_after_cleanup`, `test_decommissioned_node_cant_rejoin`, `test_topology_ops`. I'll send a fix to all of them.
