### ISSUE TITLE
Improve validation error messages

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylladb#3016]
If utf8 field validation fails, the CQL client will get:
```
marshaling error: Conversion failed
```

It's cryptic. We should mention that validation failed, for which table and which column. If possible, what was the offending position in the string.

**Comment by avelanarius** [comment]
It looks like this issue is fixed in the current version of Scylla, as shown by following experiments:

1. In `cql_query_test.cc` there is already a test checking UTF8 validation - whether an exception is thrown. 
The exception message is clear: ```exceptions::invalid_request_exception: Exception while binding column b: marshaling error: Validation failed - non-UTF8 character in a UTF8 string```

2. Tested Python Cassandra client. I wasn't quite able to bypass Python UTF8 validation, but I tested sending invalid UTF8 string as hex (`INSERT INTO (pk, v) VALUES (1, 0xff)` - `0xff` is invalid UTF8). 
The returned server-side error was clear: ```Invalid HEX constant (0xff) for "v" of type text```.

3. Modified Scylla to insert invalid UTF8 character into query body immediately after receving query via network. 
The returned server-side error to Java Datastax Cassandra client was clear: ```servererrors.ProtocolError: Cannot decode string as UTF8```. 
There is no info about which column caused the error, as the validation is done at lower level before parsing.

**Comment by haaawk** [comment]
> It looks like this issue is fixed in the current version of Scylla, as shown by following experiments:
> 
> 1. In `cql_query_test.cc` there is already a test checking UTF8 validation - whether an exception is thrown.
>    The exception message is clear: `exceptions::invalid_request_exception: Exception while binding column b: marshaling error: Validation failed - non-UTF8 character in a UTF8 string`

That's only when you use prepared statements no? When you run just "INSERT INTO ks.t(pk, v) VALUES (1, '[INVALID UTF8 CHAR]')" there is no binding and the info about the column name won't be added to the error msg, will it?

> 2. Modified Scylla to insert invalid UTF8 character into query body (inside string literal in `VALUES`) immediately after receving query via network. (`INSERT INTO ks.t(pk, v) VALUES (1, '[INVALID UTF8 CHAR]')`).
>    The returned server-side error to Java Datastax Cassandra client was clear: `servererrors.ProtocolError: Cannot decode string as UTF8`.
>    There is no info about which column caused the error, as the validation is done at lower level before parsing.

@tgrabiec Is it enough in your opinion or would you like to see more info being propagated to the driver?

**Comment by tgrabiec** [comment]
The message was improved in 6fadba56cc18bebe6648e6aec09be1b0b93f4817.

We're still missing information about the name of the column and offending position in the string.

**Comment by avelanarius** [comment]
> > It looks like this issue is fixed in the current version of Scylla, as shown by following experiments:
> > 
> > 1. In `cql_query_test.cc` there is already a test checking UTF8 validation - whether an exception is thrown.
> >    The exception message is clear: `exceptions::invalid_request_exception: Exception while binding column b: marshaling error: Validation failed - non-UTF8 character in a UTF8 string`
> 
> That's only when you use prepared statements no? When you run just "INSERT INTO ks.t(pk, v) VALUES (1, '[INVALID UTF8 CHAR]')" there is no binding and the info about the column name won't be added to the error msg, will it?

`INSERT INTO ks.t(pk, v) VALUES (1, '[INVALID UTF8 CHAR]')`
@haaawk If I just run this query (inside `cql_query_test.cc`!) there is no exception and the invalid row is inserted... (subsequent "SELECT" returns the row).

I presume that in this place validation is not performed, because in case of a "normal" query execution, the validation is done beforehand in a different place (for example `cql_transport`) - therefore it is not a "real" concern? (unit test using directly internal code):
https://github.com/scylladb/scylla/blob/1d06da18fcd9073a6ea30b8be3c428212d69cc9f/transport/request.hh#L116-L122

**Comment by haaawk** [comment]
Can we close this @avelanarius ?

**Comment by haaawk** [comment]
@avelanarius ping

**Comment by nyh** [comment]
@tgrabiec this is an issue you opened many years ago, and above you made a comment that it was improved. Has it improved enough to be closed?

**Comment by roydahan** [comment]
@bhalevy please decide if it's good enough as is and who should handle it if not.

**Comment by nyh** [comment]
I think it should be closed - the error message was improved by https://github.com/scylladb/scylladb/pull/7169, and I even wrote a test for invalid utf8 (test/cql-pytest/test_validation.py) and it claims the Scylla error message is (or was, when I wrote the test)  "Exception while binding column t: marshaling error: Validation failed - non-UTF8 character in a UTF8 string, at byte offset 0" - this seems good to me.

Note that the aforementioned test doesn't go as far as checking the text in the error message (which is also different in Scylla and Cassandra), so it will not be able to catch a regression in the quality of the error message.
